### ISSUE TITLE
Corrupted UTF-8 with selector manipulation functions

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1116] opened 2015-04-19 17:02 UTC
This is a follow-up of an issue spotted as part of a PR from @xzyfer on Sass-Compatibility: https://github.com/sass-compatibility/sass-compatibility.github.io/pull/36. 

Basically: LibSass (3.2 beta) sometimes returns corrupted UTF-8 when using selector manipulation functions (which are not implemented yet, but still). I could not reduce the code to find the actual culprit. Worse: sometimes I managed to have two different outputs with the same input. 

Anyway, @xzyfer has worked on it already, this issue is only to keep this bug in his radar.

**Comment by xzyfer** [comment] 2015-04-20 00:49
Unfortunately this issue appears to be someone environment specific. I have been update to reproduce this myself. I don't believe this is a high priority right now.

**Comment by xzyfer** [comment] 2015-04-20 01:00
I've looked into this further. The originally reported issue regarding UTF-8 corruption is a red herring. That was actually a Ruby error when trying to parse the stdout output of Libsass 3.2.0-beta.5. The issue here is that sometimes Libsass outputs garbage characters .

```
Error: unterminated argument to selector-nest(...)
        on line 1 of tests/selector_manipulation_functions/input.scss
>> �$4��
   --------------^
```

That makes this issue a duplicate of https://github.com/sass/libsass/issues/1079

**Closed by xzyfer** 2015-04-20 01:00 UTC
Labels: bug, interesting
