### ISSUE TITLE
Regression with call()

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#2057] opened 2016-04-29 07:48 UTC
The following code was working correctly up until one of the last minor bumps.
```scss
@function apply($args) { @return call($args...); }
@function foo($a, $b, $c){ @return $a $b $c; }

.fntest {
  output: call(foo,1,2,3);
  output: apply(foo 1 2 3);
}
```
Returned correctly, as late as `v3.3.4`:
```css
.fntest {
  output: 1 2 3;
  output: 1 2 3; }
```
now with `v3.3.6` returns:
```css
.fntest {
  output: 1 2 3;
  output: foo 1 2 3...(); }
```

**Comment by mgreter** [comment] 2016-04-30 04:59
Probably a duplicate of https://github.com/sass/libsass/issues/2034

**Closed** 2016-04-30 10:22 UTC
Labels: Bug - Confirmed, Bug - Regression, Dev - PR Ready, Dev - Test Written
