### ISSUE TITLE
SassScript not supported in the url() of an @import rule

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1764] opened 2015-11-27 05:15 UTC
Only happens in @import rules.  (Perhaps this is related to #1595?)

Input SCSS:
```CSS
@import url(unquote("fi" + "le.css"));
```

Ruby SASS (3.4.19)
```CSS
@import url(file.css);
```

Libsass (3.3.2)
```
Error: URI is missing ')'
        on line 1 of test.scss
>> @import url(unquote("fi" + "le.css"));
```

**Comment by xzyfer** [comment] 2015-12-01 12:17
This is a duplicate of https://github.com/sass/libsass/issues/1597

**Comment by xzyfer** [comment] 2015-12-01 12:17
Closing in favour of https://github.com/sass/libsass/issues/1597

**Closed by xzyfer** 2015-12-01 12:17 UTC
