### ISSUE TITLE
Cannot compile bootstrap 4.0.0-beta.2

### ISSUE THREAD

**Issue by pwoosam** [sass/libsass#2515] opened 2017-12-14 23:53 UTC
# Compilation of bootstrap scss results in `Error: Invalid mapping`

## input.scss
The offending file is bootstrap/mixins/_hover.scss
```scss
@mixin hover {
  // TODO: re-enable along with mq4-hover-shim
//  @if $enable-hover-media-query {
//    // See Media Queries Level 4: https://drafts.csswg.org/mediaqueries/#hover
//    // Currently shimmed by https://github.com/twbs/mq4-hover-shim
//    @media (hover: hover) {
//      &:hover { @content }
//    }
//  }
//  @else {
    &:hover { @content; }
//  }
}


@mixin hover-focus {
  @if $enable-hover-media-query {
    &:focus {
      @content;
    }
    @include hover { @content; }
  } @else {
    &:focus,
    &:hover {
      @content;
    }
  }
}
...
```

## Actual results

[todo]: # (update version info!)

node-sass version: 4.7.2
[libsass 3.5.0.beta.2][1]
```javascript
{ uid: 10,
  name: 'writeBundles',
  branch: false,
  error: Error: Invalid mapping: {"generated":{"line":246,"column":3},"source":"styles/bootstrap/mixins/_hover.scss","original":{"line":12,"column":-27},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\PWooSam\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\source-map\lib\source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\PWooSam\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\source-map\lib\source-map-generator.js:101:12)
    at C:\Users\PWooSam\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\aurelia-cli\lib\build\concat-with-sourcemaps\index.js:61:28
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\PWooSam\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Concat.add (C:\Users\<Username>\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\aurelia-cli\lib\build\concat-with-sourcemaps\index.js:59:18)
    at work.then (C:\Users\PWooSam\P5%20-%20Web%20Front%20End\src\LeadStack\node_modules\aurelia-cli\lib\build\bundle.js:215:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7),
  duration: [ 1, 939341772 ],
  time: 1513293686334 }
```

## Expected result
```
Something compiled.
```

version info:
```cmd
$ node-sass --version
node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#Ly8gc3R5bGVsaW50LWRpc2FibGUgaW5kZW50YXRpb24KQG1peGluIGhvdmVyIHsKICAvLyBUT0RPOiByZS1lbmFibGUgYWxvbmcgd2l0aCBtcTQtaG92ZXItc2hpbQovLyAgQGlmICRlbmFibGUtaG92ZXItbWVkaWEtcXVlcnkgewovLyAgICAvLyBTZWUgTWVkaWEgUXVlcmllcyBMZXZlbCA0OiBodHRwczovL2RyYWZ0cy5jc3N3Zy5vcmcvbWVkaWFxdWVyaWVzLyNob3ZlcgovLyAgICAvLyBDdXJyZW50bHkgc2hpbW1lZCBieSBodHRwczovL2dpdGh1Yi5jb20vdHdicy9tcTQtaG92ZXItc2hpbQovLyAgICBAbWVkaWEgKGhvdmVyOiBob3ZlcikgewovLyAgICAgICY6aG92ZXIgeyBAY29udGVudCB9Ci8vICAgIH0KLy8gIH0KLy8gIEBlbHNlIHsKICAgICY6aG92ZXIgeyBAY29udGVudDsgfQovLyAgfQp9CgoKQG1peGluIGhvdmVyLWZvY3VzIHsKICBAaWYgJGVuYWJsZS1ob3Zlci1tZWRpYS1xdWVyeSB7CiAgICAmOmZvY3VzIHsKICAgICAgQGNvbnRlbnQ7CiAgICB9CiAgICBAaW5jbHVkZSBob3ZlciB7IEBjb250ZW50OyB9CiAgfSBAZWxzZSB7CiAgICAmOmZvY3VzLAogICAgJjpob3ZlciB7CiAgICAgIEBjb250ZW50OwogICAgfQogIH0KfQoKQG1peGluIHBsYWluLWhvdmVyLWZvY3VzIHsKICBAaWYgJGVuYWJsZS1ob3Zlci1tZWRpYS1xdWVyeSB7CiAgICAmLAogICAgJjpmb2N1cyB7CiAgICAgIEBjb250ZW50OwogICAgfQogICAgQGluY2x1ZGUgaG92ZXIgeyBAY29udGVudDsgfQogIH0gQGVsc2UgewogICAgJiwKICAgICY6Zm9jdXMsCiAgICAmOmhvdmVyIHsKICAgICAgQGNvbnRlbnQ7CiAgICB9CiAgfQp9CgpAbWl4aW4gaG92ZXItZm9jdXMtYWN0aXZlIHsKICBAaWYgJGVuYWJsZS1ob3Zlci1tZWRpYS1xdWVyeSB7CiAgICAmOmZvY3VzLAogICAgJjphY3RpdmUgewogICAgICBAY29udGVudDsKICAgIH0KICAgIEBpbmNsdWRlIGhvdmVyIHsgQGNvbnRlbnQ7IH0KICB9IEBlbHNlIHsKICAgICY6Zm9jdXMsCiAgICAmOmFjdGl2ZSwKICAgICY6aG92ZXIgewogICAgICBAY29udGVudDsKICAgIH0KICB9Cn0K

Is there an updated version of libsass/node-sass without this error?
Is there any way to get libsass working with bootstrap 4 without downgrading to a version of libsass that requires an older version of node? (I'm on 9.0.3)

**Comment by mgreter** [comment] 2018-01-11 21:42
Closing as probable duplicate of https://github.com/sass/libsass/issues/2312
Please provide some working reproduction code to verify. Thanks.

**Closed by mgreter** 2018-01-11 21:42 UTC
