### ISSUE TITLE
Sassc has no -watch option?

### ISSUE THREAD

**Issue by patlecat** [sass/libsass#807] opened 2015-01-05 12:28 UTC
Is it true that *Sassc* has no **-watch** option at all (checked only under Windows)? I found that extremely helpful with the Ruby implementation. Is this planned anytime soon or is there a reason why it doesn't exist here?

**Comment by patlecat** [comment] 2015-01-05 12:35
Seems fairly easy to do on any platform nowadays :http://stackoverflow.com/questions/931093/how-do-i-make-my-program-watch-for-file-modification-in-c

**Comment by mgreter** [comment] 2015-01-05 17:21
Duplicate of https://github.com/sass/sassc/issues/63

Also I don't know where you read "easy" on that stackoverflow page. As you see there are 4 different APIs for every different OS. And I don't think we want to be depeding on Qt!

**Closed by mgreter** 2015-01-05 17:21 UTC
