### ISSUE TITLE
regression in importing behavior

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#1530] opened 2015-09-04 05:05 UTC
https://github.com/sass/libsass/pull/1528 caused a regressions in custom importer functions. Libsass attempts to resolve every import; failing to find the import on the file system, it throws an error. Previously, libsass would call registered imports. Registered importers set via `option_set_c_importers` are not called.

Reverting the above PR fixes the tests that are failing.

**Comment by mgreter** [comment] 2015-09-04 13:36
I cannot reproduce with perl-libsass, my spec tests with custom importer didn't show any regression!

Can you provide a sampe that shows the behavior?

**Comment by drewwells** [comment] 2015-09-04 14:38
It only affects the file compiler

**Comment by mgreter** [comment] 2015-09-04 23:17
Not sure when I get around to look into it. If you could provide another standalone C example it would greatly help me to get a fix faster, as I will have to produce a test case for myself too. IMHO it is not a release-blocker since the feature in question is still marked experimental.

**Comment by drewwells** [comment] 2015-09-04 23:53
This is definitely a blocker for me as it makes impossible to handle virtual imports that don't point to real files. It also worked just fine before this refactor.

Is there an example of using a custom importer. It would take me a long time to rewrite this behavior in c.

**Comment by mgreter** [comment] 2015-09-04 23:57
https://github.com/sass/libsass/wiki/API-Sass-Importer-Example

**Comment by drewwells** [comment] 2015-09-05 02:07
Possibly related, using the following as styles.scss in that example:

```
@import "/tmp/styles.scss";
```

Results in
```
remote {
  color: red; }

remote {
  color: red; }
```

**Comment by drewwells** [comment] 2015-09-05 03:42
Running this example, you can see the custom importer is never executed. It will work if you switch to data compiler (untested in C).

```
#include <stdio.h>
#include <string.h>
#include "sass_context.h"

Sass_Import_List sass_importer(const char* path, Sass_Importer_Entry cb, struct Sass_Compiler* comp)
{
  // get the cookie from importer descriptor
  void* cookie = sass_importer_get_cookie(cb);
  Sass_Import_List list = sass_make_import_list(1);
  printf("loooking up %s\n", path);
  char* nope = "nope{ color: blue; }";
  if (strcmp(path,"noop")!=0) {
    list[0] = sass_make_import_entry("nope.scss", strdup(nope), 0);
  } else {
    printf("no match\n");
    list[0] = sass_make_import_entry("", strdup(""), 0);
  }
  printf("exit\n");
  return list;
}

int main( int argc, const char* argv[] )
{

  // get the input file from first argument or use default
  const char* input = argc > 1 ? argv[1] : "styles.scss";

  // create the file context and get all related structs
  struct Sass_File_Context* file_ctx = sass_make_file_context(input);
  struct Sass_Context* ctx = sass_file_context_get_context(file_ctx);
  struct Sass_Options* ctx_opt = sass_context_get_options(ctx);

  // allocate custom importer
  Sass_Importer_Entry c_imp =
    sass_make_importer(sass_importer, 0, 0);
  // create list for all custom importers
  Sass_Importer_List imp_list = sass_make_importer_list(1);
  // put the only importer on to the list
  sass_importer_set_list_entry(imp_list, 0, c_imp);
  // register list on to the context options
  sass_option_set_c_importers(ctx_opt, imp_list);
  // context is set up, call the compile step now
  int status = sass_compile_file_context(file_ctx);

  // print the result or the error to the stdout
  if (status == 0) puts(sass_context_get_output_string(ctx));
  else puts(sass_context_get_error_message(ctx));

  // release allocated memory
  sass_delete_file_context(file_ctx);

  // exit status
  return status;

}
```

**Comment by mgreter** [comment] 2015-09-05 12:38
Thanks for the sample. Should be fixed with https://github.com/sass/libsass/pull/1533

**Closed** 2015-09-05 19:42 UTC
Labels: Bug - Confirmed, Bug - Regression, Dev - PR Ready, Release - Blocker
