### ISSUE TITLE
libsass build failure on FreeBSD 11.1

### ISSUE THREAD

**Issue by tony** [sass/libsass#2512] opened 2017-11-25 22:40 UTC
```
"node-sass": "^4.7.2",
```

```
pkg info node
node-8.8.1
Name           : node
Version        : 8.8.1
Installed on   : Sat Nov 25 22:21:50 2017 CST
Origin         : www/node
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : www
Licenses       : MIT
Maintainer     : bhughes@FreeBSD.org
WWW            : http://nodejs.org/
Comment        : V8 JavaScript for client and server
Options        :
        BUNDLED_SSL    : off
        DOCS           : on
        DTRACE         : on
        NLS            : on
Shared Libs required:
        libicudata.so.59
        libcares.so.2
        libicuuc.so.59
        libicui18n.so.59
        libuv.so.1
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 24.4MiB
Description    :
Node.js is a JavaScript runtime built on Chrome's V8 JavaScript
engine. Node.js uses an event-driven, non-blocking I/O model that
makes it lightweight and efficient. Node.js' package ecosystem,
npm, is the largest ecosystem of open source libraries in the world.

WWW: http://nodejs.org/
```

```
cd project/_ux && yarn install
yarn install v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "freebsd" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

error /usr/home/x/work/project/project/_ux/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /usr/home/x/work/project/project/_ux/node_modules/node-sass
Output:
Building: /usr/local/bin/node /usr/home/x/work/project/project/_ux/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/home/x/work/project/project/_ux/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | freebsd | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.8.1
gyp verb command install [ '8.8.1' ]
gyp verb install input version string "8.8.1"
gyp verb install installing version: 8.8.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.8.1
gyp verb build dir attempting to create "build" dir: /usr/home/x/work/project/project/_ux/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /usr/home/x/work/project/project/_ux/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/home/x/work/project/project/_ux/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/home/x/work/project/project/_ux/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /usr/home/x/work/project/project/_ux/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/home/x/work/project/project/_ux/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/x/work/project/project/_ux/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/x/work/project/project/_ux/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/x/.node-gyp/8.8.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/x/.node-gyp/8.8.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/home/x/work/project/project/_ux/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/x/.node-gyp/8.8.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/home/x/work/project/project/_ux/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/x/.node-gyp/8.8.1
gyp verb `which` succeeded for `gmake` /usr/local/bin/gmake
gyp info spawn gmake
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
gmake[1]: Entering directory '/usr/home/x/work/project/project/_ux/node_modules/node-sass/build'
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.0.beta.2"' -I/home/x/.node-gyp/8.8.1/include/node -I/home/x/.node-gyp/8.8.1/src -I/home/x/.node-gyp/8.8.1/deps/uv/include -I/home/x/.node-gyp/8.8.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:1:
In file included from ../src/libsass/src/sass.hpp:46:
In file included from ../src/libsass/include/sass/base.h:19:
In file included from /usr/include/c++/v1/stddef.h:40:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
gmake[1]: *** [src/libsass.target.mk:144: Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gmake[1]: Leaving directory '/usr/home/x/work/project/project/_ux/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/home/x/work/project/project/_ux/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 11.1-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/home/x/work/project/project/_ux/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/home/x/work/project/project/_ux/node_modules/node-sass
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

*** Error code 1

Stop.
make: stopped in 
````

**Comment by mgreter** [comment] 2018-01-11 01:44
Closing as duplicate of https://github.com/sass/libsass/issues/2453
Upstream bug was https://github.com/nodejs/node/issues/14076

**Closed by mgreter** 2018-01-11 01:44 UTC
