### ISSUE TITLE
difference in implementation of inspect() between libsass and sass

### ISSUE THREAD

**Issue by CHedgren** [sass/libsass#1280] opened 2015-06-16 19:28 UTC
with libsass, type-of(inspect(white)) returns color but with sass it returns string. I am guessing string is the desired result. 

see this https://gist.github.com/CHedgren/048b98d1655ea6835e4c

// ----
// libsass (v3.2.5)
// ----
 
div:after {
  content: type-of(inspect(white));
  }

outputs: 

div:after {
  content: color;
}

whereas I expected

div:after {
  content: string;
}

**Comment by chriseppstein** [comment] 2015-06-16 23:02
inspect should always return a string.

**Comment by mgreter** [comment] 2015-06-23 18:10
Duplicate of #1281

**Closed** 2015-07-08 06:10 UTC
Labels: Bug - Confirmed, Dev - PR Ready
