### ISSUE TITLE
adjust-color output different on windows and linux

### ISSUE THREAD

**Issue by gabriellecrawford** [sass/libsass#1554] opened 2015-09-18 17:55 UTC
I am using adjust-color, and it's giving me a different output on windows and linux. The color differences themselves are so subtle I doubt the eye can see it, but we have tests running that are failing due to these differences.

Here's my sass
```
$panelBorderColorSaturationAdjustment: 5% !default;
$panelBorderColorLightnessAdjustment: -5% !default;

$panel4BgColor:     #ffe4e1 !default;
$panel4BorderColor: adjust-color($panel4BgColor,
                                 $lightness: $panelBorderColorLightnessAdjustment,
                                 $saturation: $panelBorderColorSaturationAdjustment) !default;
```
the diff I get is here, the c8 is from libsass on linux (it matches the ruby output), the c7 is libsass on windows
```
<   border-color: #ffcdc8; }
---
>   border-color: #ffcdc7; } 
```

**Comment by saper** [comment] 2015-09-18 19:24
Looks like a problem with floating point representation...

**Comment by saper** [comment] 2015-09-18 19:29
Did you try ruby on Windows as well?

**Comment by saper** [comment] 2015-09-18 20:22
@gabriellecrawford which version of libsass are you using?

**Comment by gabriellecrawford** [comment] 2015-09-18 20:40
hi, yes ruby sass gives the value that ends with c8 on both windows and linux

let me look into the version question, we're using grunt-sass which uses node-sass?

My coworker said he tried running with the node-sass 3.3.3 and the problem still exists...

**Comment by gabriellecrawford** [comment] 2015-09-18 20:47
so we're using grunt 1.0.0 which I think uses node-sass 3.0.0 which uses libsass 3.2.0?

**Comment by saper** [comment] 2015-09-18 20:51
> hi, yes ruby sass gives the value that ends with c7 on both windows and linux
> 
> let me look into the version question, we're using grunt-sass which uses node-sass?
> 
> My coworker said he tried running with the node-sass 3.3.3 and the problem still exists...

Good to know you are using node-sass for that, thanks.

Can you try running "node-sass" script - it should be in the node_modules/node-sass/bin
and check version with "node-sass -v".

**Comment by saper** [comment] 2015-09-18 20:58
I just got 
```css
h1 {
  border-color: #ffcdc7; }
````
with 

````
node-sass	3.3.2	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
````

on both FreeBSD 10 and 11 running on amd64.

**Comment by saper** [comment] 2015-09-18 21:00
> so we're using grunt 1.0.0 which I think uses node-sass 3.0.0 which uses libsass 3.2.0?

Check with node-sass -v
or just run node and then

var s = require('node-sass')
console.log(s.info)

**Comment by gabriellecrawford** [comment] 2015-09-18 21:08
Hmmm. I believe the linux boxes we have are running OEL 5.

**Comment by gabriellecrawford** [comment] 2015-09-18 21:12
just to elaborate, we just switched over from running the same scss files on the same machines from running ruby sass to libsass. Ruby used to give c8 on all machines, libsass still gives c8 on our OEL machines, but c7 on windows....

**Comment by saper** [comment] 2015-09-18 21:37
I am getting `#ffcdc8` using ruby sass (git master b409aad5fb34f363cec426f2102dd7005e1a45a6) on the same machine I got `#ffcdc7`. Good to reproduce :)

**Comment by saper** [comment] 2015-09-18 21:48
Interestingly, on some random 64-bit Linux machine I tried:

````
$ ./sass/bin/sass t.scss 
h1 {
  border-color: #ffcdc8; }
$ ./node-sass/bin/node-sass t.scss 
h1 {
  border-color: #ffcdc7; }

````

**Comment by xzyfer** [comment] 2015-09-19 03:28
This a known issue of sorts. Recent version of Ruby Sass implemented a subtle rounding in colour functions to compensate. We have not applied the same fix yet.

>Improve rounding of the results of color operations.
>- 3.4.14 changelog
>http://sass-lang.com/documentation/file.SASS_CHANGELOG.html

**Comment by xzyfer** [comment] 2015-09-19 03:31
Original upstream issue https://github.com/sass/sass/issues/1690

**Comment by xzyfer** [comment] 2015-09-19 03:32
I'm going to do some big updates to how we do colours 3.4. This will be fixed as part of that.

**Comment by gabriellecrawford** [comment] 2015-09-19 04:21
Great, thank you!!!!

**Comment by saper** [comment] 2015-09-24 07:08
It is impossible to write a test for this; if we are (and it is so specified) using floating point arithmetic - I'd need to check values against ɛ. I think in this case some fixed-point integer-like arithmetic should suffice, but that's on our reference implementation to settle on something.

**Comment by xzyfer** [comment] 2015-09-24 12:09
Don't worry about a test for this. Technically we already have it with our
current colour function test coverage. We've essential disabled the rest by
locking to a version of ruby without the colour rounding.

**Comment by mgreter** [comment] 2015-11-07 01:39
Pretty sure this is related to 32 vs 64 bit builds and rounding behavior!

**Comment by mgreter** [comment] 2015-11-07 01:42
@xzyfer didn't find any spec test in the sass-spec repo, although you added the `test written` tag?

**Comment by xzyfer** [comment] 2015-11-13 19:02
This should be fixed in 3.3.2. Please reopen if the problem persists.

**Closed by xzyfer** 2015-11-13 19:02 UTC
Labels: Bug - Confirmed, Dev - Test Written

**Comment by conceptdeluxe** [comment] 2015-12-12 22:39
I think I have discovered a similar / related bug with:

sassc: 3.3.0
libsass: 3.3.2-32-gb2a3
sass2scss: 1.0.5

Input:

    $foobar-color: #f0706f;
    $foobar-bg: lighten($foobar-color, 50%);
    $foobar-border: darken($foobar-bg, 5%);
    .foobar {
        border-color: $foobar-border;
    }

Output SASS / Ruby:
    
    .foobar {
      border-color: #fde8e8; }

Output SassC / LibSass:
    
    .foobar{border-color:#f2f2f2}

**Comment by xzyfer** [comment] 2015-12-27 07:06
@conceptdeluxe you've run into an interesting caveat of how we build LibSass.

We currently test against Ruby Sass 3.4.16 which returns `#fde8e8;`. However this appears to have changed by 3.4.20 which now returns `#f2f2f2`.

This will be fixed once we're testing against the version that introduced this fix.
