### ISSUE TITLE
Segmentation fault with @extend and :global(> .sth)

### ISSUE THREAD

**Issue by tleunen** [sass/libsass#2366] opened 2017-05-02 03:55 UTC
### Title: Be as meaningful as possible in 60 chars if possible

input.scss
```scss
.item {
    display: inline-block;

    :global(> .ext-link) {
        background: #000;
    }
}

.link {
    color: red;
}

.textLink {
    @extend .link;
    padding: 0 10px;
}
```

[libsass 3.5.5] [1]
```css
Segmantation fault
```

ruby sass 3.4.21
```css
Segmantation fault
```

version info:
See https://github.com/sass/node-sass/issues/1961

**Comment by mgreter** [comment] 2017-05-20 23:55
Segfault has been fixed in libsass, but output does not match ruby sass.

**Comment by mgreter** [comment] 2017-05-22 18:51
This is basically also a duplicate of #2055 (missing specific pseudo selector behavior)

**Comment by mgreter** [comment] 2018-01-11 22:33
Closed via #2531

**Closed by mgreter** 2018-01-11 22:33 UTC
Labels: Bug - Confirmed, Dev - Test Written, Dev - WIP
