### ISSUE TITLE
Compiler error: argument `$color` of `lightness($color)` must be a color

### ISSUE THREAD

**Issue by emyarod** [sass/libsass#2015] opened 2016-04-21 08:58 UTC
It seems that [libsass 3.3.3](https://github.com/sass/libsass/releases/3.3.3) or higher throws an error when passing a color into this a function I've written:

Error:
```
argument `$color` of `lightness($color)` must be a color
Backtrace:
    sass/utils/_functions.scss:6, in function `lightness`
    sass/utils/_functions.scss:6, in function `set-text-color`
    sass/components/_buttons.scss:214
```

the function in question:
```
// dynamic text color
@function set-text-color($bg-color) {
  // if background color is light, return dark colored text
  @if (lightness($bg-color) > 50) { @return $dark-text; }
  // if background color is dark, return light colored text
  } @else { @return $light-text;  }
}
```

However, when I compile my Sass source files in [node-sass 3.4.2](https://github.com/sass/node-sass) (which uses [libsass 3.3.2](https://github.com/sass/libsass/releases/tag/3.3.2)), or if I compile using [sass.js 0.9.4](https://github.com/medialize/sass.js/releases/tag/0.9.4) (which uses [libsass 3.3.1](https://github.com/sass/libsass/releases/tag/3.3.1)), everything compiles fine.

**Comment by mgreter** [comment] 2016-04-21 09:12
Duplicate of https://github.com/sass/libsass/issues/1969 (found via search - please try to use it before opening new issues) and already fixed!

**Comment by emyarod** [comment] 2016-04-21 21:22
I apologize, the function does not contain that typo in the source. It must have occurred when I was copy pasting it, so it contains the extra brace. However, the problem still persists in [libsass 3.3.5](https://github.com/sass/libsass/releases/tag/3.3.5), which fixes issue #1969.

the correctly edited and entire function, for reference:

```
// dynamic text color
@function set-text-color($bg-color) {
  // if background color is light, return dark colored text
  @if (lightness($bg-color) > 50) { @return $dark-text; }
  // if background color is dark, return light colored text
  @else { @return $light-text;  }
}
```

```
// dynamic text colors
@function set-text-color($bg-color, $text-type) {
  // if bgc is light, return dark colored text
  @if (lightness($bg-color) > 50) {
    @if ($text-type == text) {
      @return $light-text;
    } @else if ($text-type == secondary-text) or if ($text-type == icons) {
      @return $light-secondary-text;
    } @else if ($text-type == hint-text) or if ($text-type == disabled-text) {
      @return $light-disabled-text;
    } @else if ($text-type == divider-text) {
      @return $light-divider-text;
    }
  // if bgc is dark, return light colored text
  } @else if ($text-type == text) {
    @return $dark-text;
  } @else if ($text-type == secondary-text) or if ($text-type == icons) {
    @return $dark-secondary-text;
  } @else if ($text-type == hint-text) or if ($text-type == disabled-text) {
    @return $dark-disabled-text;
  } @else if ($text-type == divider-text) {
    @return $dark-divider-text;
  }
}
```

**Comment by mgreter** [comment] 2016-04-21 21:25
[I'm sorry] [1], but I [cannot reporoduce] [2] it

[1]: http://libsass.ocbnet.ch/srcmap/#Ly8gZHluYW1pYyB0ZXh0IGNvbG9ycwpAZnVuY3Rpb24gc2V0LXRleHQtY29sb3IoJGJnLWNvbG9yLCAkdGV4dC10eXBlKSB7CiAgLy8gaWYgYmdjIGlzIGxpZ2h0LCByZXR1cm4gZGFyayBjb2xvcmVkIHRleHQKICBAaWYgKGxpZ2h0bmVzcygkYmctY29sb3IpID4gNTApIHsKICAgIEBpZiAoJHRleHQtdHlwZSA9PSB0ZXh0KSB7CiAgICAgIEByZXR1cm4gJGxpZ2h0LXRleHQ7CiAgICB9IEBlbHNlIGlmICgkdGV4dC10eXBlID09IHNlY29uZGFyeS10ZXh0KSBvciBpZiAoJHRleHQtdHlwZSA9PSBpY29ucykgewogICAgICBAcmV0dXJuICRsaWdodC1zZWNvbmRhcnktdGV4dDsKICAgIH0gQGVsc2UgaWYgKCR0ZXh0LXR5cGUgPT0gaGludC10ZXh0KSBvciBpZiAoJHRleHQtdHlwZSA9PSBkaXNhYmxlZC10ZXh0KSB7CiAgICAgIEByZXR1cm4gJGxpZ2h0LWRpc2FibGVkLXRleHQ7CiAgICB9IEBlbHNlIGlmICgkdGV4dC10eXBlID09IGRpdmlkZXItdGV4dCkgewogICAgICBAcmV0dXJuICRsaWdodC1kaXZpZGVyLXRleHQ7CiAgICB9CiAgLy8gaWYgYmdjIGlzIGRhcmssIHJldHVybiBsaWdodCBjb2xvcmVkIHRleHQKICB9IEBlbHNlIGlmICgkdGV4dC10eXBlID09IHRleHQpIHsKICAgIEByZXR1cm4gJGRhcmstdGV4dDsKICB9IEBlbHNlIGlmICgkdGV4dC10eXBlID09IHNlY29uZGFyeS10ZXh0KSBvciBpZiAoJHRleHQtdHlwZSA9PSBpY29ucykgewogICAgQHJldHVybiAkZGFyay1zZWNvbmRhcnktdGV4dDsKICB9IEBlbHNlIGlmICgkdGV4dC10eXBlID09IGhpbnQtdGV4dCkgb3IgaWYgKCR0ZXh0LXR5cGUgPT0gZGlzYWJsZWQtdGV4dCkgewogICAgQHJldHVybiAkZGFyay1kaXNhYmxlZC10ZXh0OwogIH0gQGVsc2UgaWYgKCR0ZXh0LXR5cGUgPT0gZGl2aWRlci10ZXh0KSB7CiAgICBAcmV0dXJuICRkYXJrLWRpdmlkZXItdGV4dDsKICB9Cn0=
[2]: http://libsass.ocbnet.ch/srcmap/#Ly8gZHluYW1pYyB0ZXh0IGNvbG9yCkBmdW5jdGlvbiBzZXQtdGV4dC1jb2xvcigkYmctY29sb3IpIHsKICAvLyBpZiBiYWNrZ3JvdW5kIGNvbG9yIGlzIGxpZ2h0LCByZXR1cm4gZGFyayBjb2xvcmVkIHRleHQKICBAaWYgKGxpZ2h0bmVzcygkYmctY29sb3IpID4gNTApIHsgQHJldHVybiAkZGFyay10ZXh0OyB9CiAgLy8gaWYgYmFja2dyb3VuZCBjb2xvciBpcyBkYXJrLCByZXR1cm4gbGlnaHQgY29sb3JlZCB0ZXh0CiAgQGVsc2UgeyBAcmV0dXJuICRsaWdodC10ZXh0OyAgfQp9

**Comment by emyarod** [comment] 2016-04-21 21:32
I only receive this error when compiling with node-sass or sass.js builds based on libsass [3.3.1](https://github.com/sass/libsass/releases/tag/3.3.1) or higher. I've spoken to the sass.js developer about this issue persisting in the latest release, but he was confident that the error was being thrown by libsass. Is there anything else I can provide to help you reproduce the bug?

**Comment by xzyfer** [comment] 2016-04-21 23:14
@emyarod how are you calling this function that produce the error?

**Comment by emyarod** [comment] 2016-04-22 00:14
```
argument `$color` of `lightness($color)` must be a color
Backtrace:
    sass/flattish/utils/_functions.scss:6, in function `lightness`
    sass/flattish/utils/_functions.scss:6, in function `set-text-color`
    sass/flattish/components/_buttons.scss:214
```

I'm using this function to style a element's text color based on its background color. In this instance, I'm styling buttons, whose background colors are first assigned in a Sass map and then passed into the `set-text-color` function.

Here is the referenced portion in `_buttons.scss`:

```
// flat buttons with color bg
@if #{$button-type} == 'flat-colorized-bg-button' {
  @if $background-color != $primary {
    #{$selector-name} {
      color: set-text-color($background-color, text) !important;

      @include ripple($background-color, $ripple-color);

      &:hover { background-color: $hover-color !important; }
    }
  } @else {
    $flat-colorized-bg-button-selectors: append($flat-colorized-bg-button-selectors, unquote('#{$selector-name}'), 'comma');
  }
}
```

If more context is required, here is the source for [`_functions.scss`](https://github.com/emyarod/flattish/blob/master/style/utils/_functions.scss) and [`_buttons.scss`](https://github.com/emyarod/flattish/blob/master/style/components/_buttons.scss)

Please let me know if any additional information is needed!

**Comment by mgreter** [comment] 2016-04-22 00:59
I would suggest to try to compile it with official ruby sass ...

**Closed** 2016-04-22 01:02 UTC

**Comment by emyarod** [comment] 2016-04-22 03:39
When compiling using the official Ruby Sass compiler, this error is thrown:

```
Error: $color: null is not a color for `lightness'
        on line 6 of utils/_functions.scss
        from line 10 of flattish.scss
  Use --trace for backtrace.
```

**Comment by slidenerd** [comment] 2021-09-17 13:07
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                               friendly-errors 18:36:40
SassError: argument `$color` of `lightness($color)` must be a color
        on line 58 of node_modules/bulma/sass/components/message.sass, in function `lightness`
        from line 58 of node_modules/bulma/sass/components/message.sass
        from line 10 of node_modules/bulma/sass/components/_all.sass
        from line 7 of node_modules/bulma/bulma.sass
        from line 101 of assets/styles/app.scss
>>       $color-lightning: max((100% - lightness($color)) - 2%, 0%);

Gives me this error
