### ISSUE TITLE
Strange issue when using 'notif' word in keyframes name

### ISSUE THREAD

**Issue by sqal** [sass/libsass#897] opened 2015-02-21 11:40 UTC
Just look at the example:

http://sassmeister.com/gist/3aec68cc752bf9ba3da9

Animation name is compiling to false. From what I see this is happening when we begin keyframes name from word 'notif'. There's no error using ruby sass.

**Comment by xzyfer** [comment] 2015-02-21 11:42
Thanks for the report. This is a duplicate of https://github.com/sass/libsass/issues/873

**Closed by xzyfer** 2015-02-21 11:42 UTC
