### ISSUE TITLE
Multiline strings with backslashes are silently truncated

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#942] opened 2015-03-13 14:13 UTC
I have helpers like this in some of my code. These used to work fine, but are now silently truncated (no errors) so that anything after the slash and newline isn't included as part of the variable.

```scss
$media-medium: "screen and (min-width: #{$break-medium-min}) \
and (max-width: #{$break-medium-max})";
```

I can provide a sass-spec PR a bit later.

**Comment by anlutro** [comment] 2015-03-13 14:19
Oddly enough, the above now works when I remove the `\` - maybe this is intentional? I actually prefer it without the `\`, but I still feel that it should be allowed - if it's not too much work to implement.

**Comment by mgreter** [comment] 2015-03-13 14:21
Libsass now much more correctly parses escaped chars. Maybe ruby sass has a special rule for lines with trailing backslashes, which I probably didn't encounter when I did the refactoring. Anyway, seems easy enough to support. But in term of CSS the backslash there does not make much sense IMO!

**Comment by anlutro** [comment] 2015-03-13 14:25
https://github.com/sass/sass/issues/1237 may be of interest regarding the backslash. It was my understanding that backslashes to denote multiline strings was valid CSS and should therefore be valid Sass/SCSS.

**Comment by xzyfer** [comment] 2015-03-16 07:47
Spec added https://github.com/sass/sass-spec/pull/278

**Comment by am11** [comment] 2015-04-03 13:48
I can reproduce this issue with current master. 
In other words, sass/sass-spec#278 is failing.

**Comment by mgreter** [comment] 2015-04-07 18:18
Unfortunately I, Travis-CI and Appveyor cannot reproduce the issue.
@am11 I'm going to close this since we have this CI tested!
Please open a new issue with your output if problem persists!

**Closed by mgreter** 2015-04-07 18:18 UTC
Labels: bug, test written

**Comment by am11** [comment] 2015-04-07 18:29
@mgreter, this only happens when git is configured to auto-correct endings. Lets say you type/paste the following in notepad:

```scss
$media-medium: "screen and (min-width: #{$break-medium-min}) \
and (max-width: #{$break-medium-max})";
```

notepad will surely add `\r\n`. :sunglasses:

**Comment by mgreter** [comment] 2015-04-07 18:36
Can you open a new issue for that with expected and actual output! Thanks!

**Comment by am11** [comment] 2015-04-07 18:49
@mgreter done https://github.com/sass/libsass/issues/1067. :)

**Comment by xzyfer** [comment] 2015-04-08 00:47
There used to be a couple specs dealing with windows line ending but I fear that may have broken since we've auto generated the specs a couple times recently.
