### ISSUE TITLE
`index()` treats both numbers with and without units as the same value.

### ISSUE THREAD

**Issue by oscarmarcelo** [sass/libsass#2810] opened 2019-01-02 18:28 UTC
LibSass `index()` treats both numbers with and without units as the same value.
For example: `1 == 1px`.

## input.scss

```scss
test {
  content: inspect(index(true 1, 1px));
}
```

## Actual results

[libsass 3.5.2][1]
```css
test {
  content: 2; }
```

## Expected result

dart sass 1.6.2
```css
test {
  content: null; }
```

Ruby also has the same error: sass/ruby-sass#106

ruby sass 3.7.2
```css
test {
  content: 2; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY2FzZTogaW5zcGVjdChpbmRleCh0cnVlIDEsIDFweCkpOwp9

**Comment by nex3** [comment] 2019-06-03 16:14
I believe this is a duplicate of https://github.com/sass/libsass/issues/2415

**Comment by mgreter** [comment] 2019-06-17 21:10
Closing as duplicate of #2415

**Closed** 2019-06-17 21:10 UTC
