### ISSUE TITLE
Segmentation fault and erroneous errors reported for interpolations in certain comments

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1798] opened 2015-12-22 05:45 UTC
When a comment appears in a location where it will not be output, interpolations inside the comment should be neither evaluated *nor* tokenized.

As far as I can tell, only the interpolations in comments which appear at the beginning of a file or following a `{` `}` or `;` should be recognized as interpolations; the rest (including comments nested within interpolations) must be parsed as plain old comments.

However, it appears that Libsass attempts to tokenize all interpolations, regardless of whether they will be output or not.  One particular case, where the interpolation contains a single quote character, causes a segfault:

Case 1:
```
a /*#{"}*/ {
  margin: 2px;
}
```

Libsass Output:
```
Segmentation fault: 11
```

Here are some other cases which do not cause Libsass to crash, but nevertheless are inconsistent with Ruby SASS:

Case 2: Valid in Ruby, Error in Libsass:
```
a /*#{#{*/ {
  margin: 2px;
}
```

Case 3: Valid in Ruby, Error in Libsass:
```
a  {
  content: "#{ a /*#{"}*/ }";
}
```

It seems unlikely that anyone would write code like this intentionally (except maybe the first case to be malicious) but it could be problematic when commenting out portions of a line that contain interpolations.

**Comment by xzyfer** [comment] 2015-12-27 07:31
Sometimes I wonder what kind of Sass you're writing @andrew-skybound .

Spec added https://github.com/sass/sass-spec/pull/652

**Comment by saper** [comment] 2015-12-31 01:30
This is amazing, thanks!

**Comment by mgreter** [comment] 2016-01-06 21:35
I cannot reproduce the segfault. The rest should be fixed by https://github.com/sass/libsass/pull/1830. There probably are more similar cases, this only touches the case with parsing an interpolated selector list. So more spec tests would be welcome ...

**Closed** 2016-01-09 06:01 UTC
Labels: BLOCKED, Bug - Interpolation, Dev - Test Written
