### ISSUE TITLE
str-slice doesn't work properly in a particular case

### ISSUE THREAD

**Issue by SFlo** [sass/libsass#987] opened 2015-03-26 10:59 UTC
`str-slice` doesn't work when the "start" is equal to the length of the string and the third parameter of str-slice is not set.
Example here : https://gist.github.com/SFlo/e5abab4ecbae5e035a35

It seems to be the same issue of #565.

**Comment by mgreter** [comment] 2015-03-27 14:33
IMO this is about two seperate issues - one was fixed quite some time ago, but there is a new regressions in #988, that this sample also suffers from. With the PR in #989 this should be solved!

Going to close this as a duplicate of #988 !

**Closed by mgreter** 2015-03-27 14:33 UTC
