### ISSUE TITLE
Unable to assign '&' as variable value

### ISSUE THREAD

**Issue by febLey** [sass/libsass#907] opened 2015-02-24 10:16 UTC
The compiler throws an error, if you try to assign a variable with the value of '&'.
Here an example:
```
.selector
  $self: &
  &--hidden
    #{$self}__child
```
The expected output should look like this
```
.selector--hidden .selector__child {
  background: white;
}
```
But as far as i know this does only work in **Sass 3.4**

**Comment by xzyfer** [comment] 2015-02-24 12:37
Thanks for the report @febLey . This is a duplicate of https://github.com/sass/libsass/issues/548

**Closed by xzyfer** 2015-02-24 12:37 UTC
