### ISSUE TITLE
`@extend`ing `selector` & `:not(selector)` won't compile

### ISSUE THREAD

**Issue by jdsteinbach** [sass/libsass#2130] opened 2016-07-21 22:38 UTC
### `@extend`ing `selector` & `:not(selector)` won't compile

[View in Sassmeister](http://www.sassmeister.com/gist/c03c05d6966c58ce84c1e7910b321322)

Yes, I realize the code below isn't logical. :) I worked around it & my code compiles fine now. 

But in Ruby Sass, it compiles without error as I expected. In libsass (running in `gulp-sass`), I got a `bus error`. Sassmeister also hangs when I attempt to use its libsass (3.5.6) compiler.

input.scss
```scss
.section-title {
  text-transform: uppercase;
}

.section {
  h2:not(.section-title) {
    @extend .section-title;
  }
}
```

[libsass 3.5.6] [1]
```css
bus error / no completion
```

ruby sass 3.4.21
```css
.section-title, .section h2:not(.section-title) {
  color: #444;
}
```

version info:
```cmd
gulp-sass@2.3.2
node-sass@3.8.0
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by jdsteinbach** [comment] 2016-07-21 22:41
I did not have this error back in March & earlier. Don't know what version of `node-sass` I had installed back then, sorry.

**Comment by xzyfer** [comment] 2016-08-04 11:13
I can confirm in v3.6.0 there was a segfault. With latest master it produces the following incorrect output.

```
.section-title, .section h2:not(.section-title):not(.section h2:not(.section-title)) {
  text-transform: uppercase; }
```

This output is due to to a know bug https://github.com/sass/libsass/issues/2055. Closing this as a duplicate.

**Closed by xzyfer** 2016-08-04 11:13 UTC
