### ISSUE TITLE
bootstraping

### ISSUE THREAD

**Issue by dilyanpalauzov** [sass/libsass#2600] opened 2018-03-18 14:37 UTC
On my system I do not have sassc, and want to compile first libsass, to get then a C wrapper.

Wit libsass-3.5.2, running ./configure creates a file  called `$(SASS_SASSC_PATH)/.deps/tester-sassc.Po`.  Subsequent invocation of make complains it cannot find `/.deps/tester-sassc.Po`.  

configure.ac shall not put this file in a directory called `$(SASS_SASSC_PATH)`.  With the latter I do not mean the the value of the expanded variable, but literally `$(SASS_SASSC_PATH)`

Then `make` shall look for the file in the current directory and not `/`.

**Comment by mgreter** [comment] 2018-03-18 22:17
Should be fixed with https://github.com/sass/libsass/pull/2601

**Closed by mgreter** 2018-03-18 22:17 UTC

**Comment by dilyanpalauzov** [comment] 2018-03-19 08:28
With the newest code, ./configure still creaes a file `$(SASS_SASSC_PATH)/.deps/tester-sassc.Po` and make says `sassc//.deps/tester-sassc.Po` not found.

**Comment by mgreter** [comment] 2018-03-19 09:27
Just made a quick test with a clean repo and can't reproduce:
```bash
git clone https://github.com/sass/libsass
cd libsass
./configure --disable-tests --disable-shared --prefix=/usr
make -j12
```

Are you sure your repo is clean and does not contain old .dep stuff from previous autoconf runs?

**Comment by dilyanpalauzov** [comment] 2018-03-19 09:49
Yes, I am sure.  `./configure` generates the attached [config.status](https://github.com/sass/libsass/files/1824452/config.status.txt) and running it creates `$(SASS_SASSC_PATH)/.deps/tester-sassc.Po`.

**Comment by mgreter** [comment] 2018-03-19 10:13
I know it creates the file, but my make does not complain it could not find the file !?
