### ISSUE TITLE
invalid quotes around "normal" line-height in font shorthand property

### ISSUE THREAD

**Issue by mahtd** [sass/libsass#1570] opened 2015-09-23 05:22 UTC
This is a regression in 3.3.0 beta from 3.2.5

Specifying `font: <font-size>/<line-height> <font-family>` works fine, but adding of the other properties to the `font` shorthand results in quotes around the `line-height` when the `normal` keyword is used. This is considered invalid by the browser (at least in Chrome and Firefox) and property is ignored.

Input:

```
a {
    font: 12px/normal serif;
}

b {
    font: normal 12px/normal serif;
}
```

Output libsass 3.2.5:

```
a {
  font: 12px/normal serif; }

b {
  font: normal 12px/normal serif; }
```

Output libsass 3.3.0-beta2:

```
a {
  font: 12px/normal serif; }

b {
  font: normal 12px/"normal" serif; }
```

**Comment by saper** [comment] 2015-09-23 07:57
Testcase added with https://github.com/sass/sass-spec/issues/512

**Comment by mahtd** [comment] 2015-09-24 06:22
Looks like 06ad34e is the one that broke it

**Comment by xzyfer** [comment] 2015-09-27 12:45
I cannot reproduce on 997c86d0f479b11da8abf87b62cadcd06f915288

**Comment by xzyfer** [comment] 2015-09-27 12:51
My mistake.

**Comment by xzyfer** [comment] 2015-09-29 16:28
I have a fix for this. Will publish when I'm home.

**Closed** 2015-09-30 13:10 UTC
Labels: Bug - Confirmed, Bug - Regression, Dev - PR Ready, Dev - Test Written, Release - Blocker
