### ISSUE TITLE
Support @use

### ISSUE THREAD

**Issue by wisniewski94** [sass/libsass#3005] opened 2019-10-15 11:56 UTC
From SASS docs:

> Only Dart Sass currently supports @use. 

[@use](https://sass-lang.com/documentation/at-rules/use#configuring-modules)

**Comment by mgreter** [comment] 2019-10-15 11:57
Duplicate of https://github.com/sass/libsass/issues/2807

**Closed by mgreter** 2019-10-15 11:57 UTC
