### ISSUE TITLE
Singularity fails to compile with error: "function output-isolation has no parameter named $span". (libSass 3.2.0)

### ISSUE THREAD

**Issue by OnkelTem** [sass/libsass#1128] opened 2015-04-24 12:48 UTC
I hope I selected the correct issue queue for this report.
On the latest libSass (3.2.0) SGS (1.6.2) fails to compile with this error:
```
Error: libraries/singularity/stylesheets/singularitygs/_api.scss
  59:87  function output-isolation has no parameter named $span
```

The next code is responsible for this (line marked with *):
```sass
  @if $Direction == 'both' or $From == 'left' or ($Direction == 'rtl' and $From == 'opposite') {
      $Left: call('output-#{$output-style}', map-merge($Span-Map, ('direction': left))); /***/
    }

    @if $Direction == 'both' or $From == 'right' or ($Direction == 'ltr' and $From == 'opposite') {
      $Right: call('output-#{$output-style}', map-merge($Span-Map, ('direction': right)));
    }
```

The function output-isolation is defined like this:
```sass
@function output-isolation($Span-Map) {
  ...
```

Ideas what is going wrong and how to workaround it?

**Comment by xzyfer** [comment] 2015-04-24 14:45
Hi @OnkelTem thanks for the report.

Unfortunately we're not able to progress on this issue in it's current state. Noone on the Libsass team is familiar with Signularity, nor do we have time to debug their entire code base.

Please supply a copy-pastable snippet of Sass code that produces the error you're encounter. Only then can we begin to understand the actual problem you're encountering.

**Comment by OnkelTem** [comment] 2015-04-24 15:06
Ok, working on this

**Comment by xzyfer** [comment] 2015-04-24 15:23
Appreciate it @OnkelTem

**Comment by Snugug** [comment] 2015-04-24 18:46
I happen to know quite a bit about Singularity, and I'm not entirely sure what's going on. I believe the problem is related to argument handling for dynamic `call` function.

The file in question is [here](https://github.com/at-import/Singularity/blob/1.x.x/stylesheets/singularitygs/_api.scss), but I believe the operative lines are [L35-47](https://github.com/at-import/Singularity/blob/1.x.x/stylesheets/singularitygs/_api.scss#L35-L47) and [L59](https://github.com/at-import/Singularity/blob/1.x.x/stylesheets/singularitygs/_api.scss#L59) where the actual call takes place.

If I were a guessing man, I think the problem is we're passing a map in to the arguments for a dynamic `call` function and that map is being converted to arguments instead of being passed as a single argument that is a map.

Here is a [working SassMeister](http://sassmeister.com/gist/8b225015987428ab92c6) using Ruby Sass, it'll fail when using the current beta of Libsass (and interestingly works with Libsass 3.1.0) so this should be a regression.

**Comment by xzyfer** [comment] 2015-04-25 01:06
You're absolutely correct @Snugug. I've opened an issue with Libsass track this https://github.com/sass/libsass/issues/1133

**Comment by xzyfer** [comment] 2015-04-26 15:04
This was fixed in https://github.com/sass/libsass/pull/1135 and will be in the next release.

**Closed by xzyfer** 2015-04-26 15:04 UTC
Labels: bug
