### ISSUE TITLE
SyntaxError using CSS fraction (fr) unit

### ISSUE THREAD

**Issue by SnijderC** [sass/libsass#2828] opened 2019-02-14 13:15 UTC
I'm tyring to create a CSS grid with the shorthand `grid`. I have no clue as to why this might happen as I don't know how SASS works internally. Hope someone can immediately spot an error on my part, or if this is an actual bug, reporting it is helpful.

__UPDATE__: Since reporting this I have come to realise that this probably has nothing specifically to do with `grid`, because it does not happen when `$width--col-1: 1rem;` as opposed to `$width--col-1: 1fr;`. So probably this has something to do with the fraction unit? Link to [libsass.ocbnet.ch/srcmap/](http://libsass.ocbnet.ch/srcmap/#JHdpZHRoLS1jb2wtMTogMXJlbTsKJHdpZHRoLS1jb2wtMjogNnJlbTsKJHdpZHRoLS1jb2wtMzogNnJlbTsKJHdpZHRoLS1jb2wtNDogMTByZW07CiRyb3ctaGVpZ2h0OiA0cmVtOwoucm93IHsKICAgIGdyaWQ6CiAgICAgICJjb2wxIGNvbDIgY29sMyBjb2w0IgogICAgICAkcm93LWhlaWdodCAvCiAgICAgICR3aWR0aC0tY29sLTEKICAgICAgJHdpZHRoLS1jb2wtMgogICAgICAkd2lkdGgtLWNvbC0zCiAgICAgICR3aWR0aC0tY29sLTQ7Cn0K) without the fraction unit (works fine).

## input.scss

```scss
$width--col-1: 1fr;
$width--col-2: 6rem;
$width--col-3: 6rem;
$width--col-4: 10rem;
$row-height: 4rem;
.row {
    grid:
      "col1 col2 col3 col4"
      $row-height /
      $width--col-1
      $width--col-2
      $width--col-3
      $width--col-4;
}
```

## Actual results

Manually constructed link, no output generated, but the error message is the same.
[libsass: 3.5.2][1] 
```
Error: 4rem/fr isn't a valid CSS value.
        on line 8 of stdin
>>       "col1 col2 col3 col4" $row-height /
   ----------------------------^
```

## Expected result

```css
grid: "col1 col2 col3 col4" 4rem / 1fr 6rem 6rem 10rem;
```

version info:
```cmd
$ sassc -v
sassc: 3.4.2
libsass: 3.4.3
sass2scss: 1.1.0
sass: 3.4
```

### Note

- My local version is as above but this was also tested against `3.5.2`.
- The newlines are not the cause of this issue, you the following leads to the same
error:

  ```scss
  $width--col-1: 1fr;
  $width--col-2: 6rem;
  $width--col-3: 6rem;
  $width--col-4: 10rem;
  $row-height: 4rem;
  .row {
      grid: "col1 col2 col3 col4" $row-height / $width--col-1 $width--col-2 $width--col-3 $width--col-4;
  }
  ```

[1]: http://libsass.ocbnet.ch/srcmap/#JHdpZHRoLS1jb2wtMTogMWZyOwokd2lkdGgtLWNvbC0yOiA2cmVtOwokd2lkdGgtLWNvbC0zOiA2cmVtOwokd2lkdGgtLWNvbC00OiAxMHJlbTsKJHJvdy1oZWlnaHQ6IDRyZW07Ci5yb3cgewogICAgZ3JpZDoKICAgICAgImNvbDEgY29sMiBjb2wzIGNvbDQiCiAgICAgICRyb3ctaGVpZ2h0IC8KICAgICAgJHdpZHRoLS1jb2wtMQogICAgICAkd2lkdGgtLWNvbC0yCiAgICAgICR3aWR0aC0tY29sLTMKICAgICAgJHdpZHRoLS1jb2wtNDsKfQo=

**Comment by SnijderC** [comment] 2019-02-14 13:38
If anyone comes across this that has the same issue, this is my current workaround:

```scss
.row {
  $width--col-1: 1fr;
  $width--col-2: 6rem;
  $width--col-3: 6rem;
  $width--col-4: 10rem;
  $row-height: 4rem;
  grid-template-areas: "col1 col2 col3 col4";
  grid-template-rows: $row-height;
  grid-template-columns: $width--col-1 $width--col-2 $width--col-3 $width--col-4;
}
```

**Comment by mgreter** [comment] 2019-04-04 13:30
You are asking sass to do a division via `/ ` and the "units" are not compatible for a division, hence you see the error message. Closing this since ruby sass gives the same error, so this is the expected behavior.

See https://github.com/sass/sass/issues/2565 for further discussions.

**Closed by mgreter** 2019-04-04 13:30 UTC

**Comment by SnijderC** [comment] 2019-05-22 10:52
> You are asking sass to do a division via / and the "units" are not compatible for a division

I understand but this is now valid ([mozilla reference](https://developer.mozilla.org/en-US/docs/Web/CSS/grid), [w3 reference](https://www.w3.org/TR/css-grid-1/#grid-shorthand)) CSS and IIRC Sass is supposed to be a superset of CSS, any valid CSS code was originally supposed to be valid Sass code right? I understand the conundrum here but as it stands valid CSS syntax is broken in Sass..

> Closing this since ruby sass gives the same error, so this is the expected behaviour.

Should I raise the issue in to Ruby Sass instead?

If it is unfixable, i.e. CSS never used the `/` operator before now so Sass can only interpret it the Sass way, then IMO there should at least be a better workaround than using specific CSS properties.

**Comment by mgreter** [comment] 2019-05-22 19:12
That's why sass/sass#2565 tries to deprecate this behavior in sass.

**Comment by SnijderC** [comment] 2019-06-13 08:03
I see, I guess I should have some patience and apply the workaround for the time being.
