### ISSUE TITLE
C API: Access @warn, @debug and Deprecation Warnings Output

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#1779] opened 2015-12-09 03:37 UTC
When a stylesheet contains `@warn`, `@debug` or when deprecation warnings are warranted, it looks like Libsass currently just spits those directly to stderr. (At least, I can't find a way to access that output from the C API. The `sass_context_get_error_message()` function does not return them, etc.)

This is not ideal because implementors may want to access and present these warnings in a different way. Say, for example, in the UI of an application. I propose a function such as `sass_context_get_warning_message()` which would return a string that simply serializes each warning/debug/deprecation statement that was encountered, or null if none were. Likewise, the JSON equivalent of this method would return an array of the encountered messages. 

My apologies if I've missed the way this is implemented already.

**Comment by mgreter** [comment] 2015-12-09 10:16
You should be able to [define a custom function like `@warn`] [1] to handle these.

[1]: https://github.com/sass/libsass/blob/master/docs/api-function.md#special-signatures

**Comment by mgreter** [comment] 2016-01-09 07:33
Closing this since it IMO should work by overloading the functions I mentioned some time ago.

**Comment by bdkjones** [comment] 2016-01-09 08:30
Would the message associated with the @debug or @warn statement be in the s_args parameter, then? 

The docs on custom functions are a little sparse (and also mention that everything is experimental).

**Comment by mgreter** [comment] 2016-01-09 08:39
AFAIR this is correct, you should get passed a sass string value for each call to `@debug` or `@warn`.

**Comment by bdkjones** [comment] 2016-01-09 08:39
For example, the `Sass_Value` union has structs for `Sass_Warning` (which I assume would be used for @warn statements?), but what gets used for @debug? Is that a `Sass_String`? I know these must seem like really dumb questions if you're someone who's intimately familiar with the Libsass source, but from the outside, the custom functions are a little tough to grok.

**Comment by bdkjones** [comment] 2016-01-09 08:55
Also: the docs state that my custom function *must* return a value. In this case, all my function does is look at the string associated with the @warn or @debug statement and record that string somewhere so I can display it in a UI. What is the appropriate value to return in this instance?

The custom function example always returns "42px". But if I return some sort of string, is that going to wind up in the output?

**Comment by mgreter** [comment] 2016-01-09 09:02
I guess that's where the experimental part really starts. You don't need to return something in these functions (you should be able to `return 0`). The magic is actually done in the [eval stage] [1]. I also just checked [`to_c` converter] [2] and you probably get `Custom_Warning` and `Custom_Error` values.
As already noted, it's still pretty much experimental.

[1]: https://github.com/sass/libsass/blob/master/src/eval.cpp#L321-L337
[2]: https://github.com/sass/libsass/blob/master/src/to_c.cpp#L15-L19

**Comment by bdkjones** [comment] 2016-01-09 09:06
Interesting. So the Sass_Value won't actually be one of the structs listed in the union, but rather a string directly? Is that behavior that's going to change?

**Comment by mgreter** [comment] 2016-01-09 09:07
No, you get a sass value of type custom warning or custom error.

**Comment by bdkjones** [comment] 2016-01-09 09:12
I see, so `Custom_Error` is used for @debug statements? And both have a message property. And returning 0 should work, maybe? :)

**Comment by mgreter** [comment] 2016-01-09 09:17
You should just check the kind of values you get via the [sass values api] [1]. I guess you probably get the type you pass during the calls. So if you call `@debug(1, "asd")` you probably get a `s_args` list with two arguments with one of type number and the other of type string. I don't for sure.

[1]: https://github.com/sass/libsass/blob/master/docs/api-value.md

**Comment by saper** [comment] 2016-01-09 12:33
Reopening to check this.

**Comment by mgreter** [comment] 2016-01-09 12:38
Check what?

**Comment by saper** [comment] 2016-01-09 12:44
Check how actually @warn and @debug objects are returned alongside the "normal" value

**Comment by mgreter** [comment] 2016-01-09 12:54
Since the functions are called like regular sass functions, I'm pretty positive you get a list of sass values in s_args as with all other functions. Return value is ignored. Feel free to re-open if this is not the case :wink:

**Closed by mgreter** 2016-01-09 12:54 UTC
Labels: C API

**Comment by bdkjones** [comment] 2016-01-10 04:05
Okay, so `s_args` will be a list. Now suppose I use the example from the Sass docs for debug:

    @debug 10em + 12em;

This is supposed to return:

    Line 1 DEBUG: 22em

In Libsass, is this going to be a single string? Or am I going to get a bunch of different value types where "line" is a string, "1" is a number, "DEBUG:" is a string, 22 is a number and "em" is a string? I'm just a bit confused because @debug and @warn output strings, but the above makes it sound like they could potentially output a list of all kinds of values, which makes dealing with the output much harder.

And finally: I still vote that @warn and @debug should not be second-class citizens in Libsass. They are both primary features of Sass and the compiler should have built-in support for them without requiring each implementor to build that support themselves. (It's also safer: no one is in a better position to properly implement these functions than the Libsass team.)

**Comment by bdkjones** [comment] 2016-01-10 04:42
I've written a custom function to handle @warn. `s_args` is indeed a list and I can walk through it and pull out the string from the @warn message. However, the line number and file from which that message was pulled are not in s_args. This is kind of critical information to have. Is there an API to get it?

**Comment by bdkjones** [comment] 2016-01-10 04:45
I've written a custom function to handle @debug, using the example above from the official Sass docs (a simple 10em + 12em) 

 `s_args` is indeed a list, with length 1. However, when I attempt to handle that value I find that it is NOT any of these: `Sass_String, Sass_Warning, Sass_Error, Sass_List, Sass_Map`. I have not tested `Sass_Boolean, Sass_Number, Sass_Color, etc` because those seem really unlikely.

So... how do I get the @debug statement out of `s_args`? And, additionally, I think the same problem with the filename and line number from @warn will apply here as well.

**Comment by bdkjones** [comment] 2016-01-10 05:06
Looking at the link you posted (https://github.com/sass/libsass/blob/master/src/eval.cpp#L321-L337), it appears that the backtrace is never available to the custom function that handles @warn. That's a pretty big limitation and, IMO, renders the "use a custom function to handle @warn and @debug" an unworkable approach. Perhaps re-open until this limitation is addressed?

**Comment by mgreter** [comment] 2016-01-10 15:03
`10em + 12em` should resolve to a number of `22em`, so yes, I expect you get a number there (what if you would want your own version of sprintf). Thought this was obvious, `@debug(1px+2px, "foo" + bar, 5 > 3)` should IMO give a list of `3px, "foobar", true` which are of type `number, string, boolean`.

As for the parser information (line numbers etc), this would be a duplucate of https://github.com/sass/libsass/issues/1037

**Comment by bdkjones** [comment] 2016-01-10 18:47
I see. What threw me off was the "em". I expected 12em to be a string because of the presence of "em", which isn't a number.

**Comment by xzyfer** [comment] 2016-01-12 11:15
Overloading these functions feels hacky. IMHO we should expose a dedicated interface for user defined `@debug`, `@error`, and `@warn` that multiple listeners can be registered to be notified when called.

**Comment by DaSchTour** [comment] 2017-02-02 11:55
Shouldn't this be reopened immediately? It looks like this missing API makes all build wrappers just spit out errors although they are warnings which is a really ugly behavior and gives little chance to determine if a real error happened or it's just some warning that could be ignored. This then leads to the fact, that frameworks often don't use `@warn` to prevent errors although they might have pretty important information.

**Comment by saper** [comment] 2017-02-02 12:03
@xzyfer I actually wish we've had a two-way communication with libsass but that is unlikely to happen at this stage. That would solve our node-sass threadpool problems.

@DaSchTour Nobody has actually tried how that works with the suggested albeit hacky solution. I actually wonder how this could be done properly - via some kind of callbacks? or should errors be part of the information returned?

**Comment by DaSchTour** [comment] 2017-02-02 12:28
@saper I really don't care how this is done. I just think that it is very important to have a proper log and log level handling. I haven't seen such a worse log handling in any other library that is that wide spread.

**Comment by xzyfer** [comment] 2017-02-02 12:35
For reference this started in https://github.com/sindresorhus/grunt-sass/pull/273.

@DaSchTour I honestly have no idea what you're asking for. Nothing has changed with regards to `@warn` or `@error` in a long time. We act exactly has Sass does. I also agree with @sindresorhus that your PR isn't addressing the problem.

Please provide a real example of the issue you're experiencing.

**Comment by xzyfer** [comment] 2017-02-02 12:42
I think I understand the issue. https://github.com/sindresorhus/grunt-sass/pull/273#issuecomment-276947219

It's unrelated to this issue so please comment on the grunt-sass issue, not here.

**Comment by DaSchTour** [comment] 2017-02-02 13:10
@xzyfer well the problem is, that while framework using SASS evolve they add features to assists developers in the way, that they add `@warn` to notify the developer of possible problems. But since they are only warning they shouldn't be errors and there should be the possibility to detect and quit them like it is described in SASS reference. But in fact it's not possible because nobody knows whats going on. Something is thrown into the log and everything is treated like an error. It's even somehow random if this errors lead to breaking execution or not. I've seen so much different behaviors in the last months. So I'm always in fear that this warning may break our build and then we will have to add a `@try {} @catch {}` to our scss to prevent warnings from breaking build execution. On top of this I don't like to bother all developers with warning that I can't and will not solve immediately.

**Comment by xzyfer** [comment] 2017-02-02 13:11
@DaSchTour please see my comment sindresorhus/grunt-sass#273 (comment). This issue is not related.
