### ISSUE TITLE
@at-root (without: media) selector outside from wapper

### ISSUE THREAD

**Issue by sou-lab** [sass/libsass#1890] opened 2016-01-21 08:16 UTC
When use "@at-root (without: media)".
`.box` is outside from `.wrap`

``` scss
.wrap {
  @media (min-width: 480px) { 
    display: block;
    @at-root (without: media){ 
      .box { 
        display: inline-block;
      }
    } 
  }
}
```

LibSass

``` css
@media (min-width: 480px) {
  .wrap {
    display: block;
  }
}

.box {
  display: inline-block;
}

```

Ruby Sass 3.4

``` css
@media (min-width: 480px) {
  .wrap {
    display: block;
  }
}
.wrap .box {
  display: inline-block;
}
```

Spec added https://github.com/sass/sass-spec/pull/749
##

**Comment by sou-lab** [comment] 2016-01-21 08:22
if `.box` at root

```scss
.wrap {
  @media (min-width: 480px) { 
    display: block;
    @at-root (without: media rule) {
    // or  @at-root (without: all) {
      .box { 
        display: inline-block;
      }
    } 
  }
}
```

**Comment by mgreter** [comment] 2016-01-21 10:30
This is basically a duplicate of https://github.com/sass/libsass/issues/1661 and https://github.com/sass/libsass/issues/1873

**Comment by xzyfer** [comment] 2016-05-21 14:18
I've compared our at-root implementation with Ruby Sass. The at-root is being resolved correctly in this case. The problem here is that the `.box` selector is not fully resolved (parentized) in the expand/eval stage.

**Comment by mgreter** [comment] 2018-01-11 22:05
Related to https://github.com/sass/libsass/issues/2444 and https://github.com/sass/libsass/issues/1651

**Closed** 2018-12-06 11:31 UTC
Labels: Bug - @at-root with/without, Bug - Confirmed, Dev - Test Written, Sass 3.4 Compatibility
