### ISSUE TITLE
adjust-color() does not change anything

### ISSUE THREAD

**Issue by binarykitchen** [sass/libsass#1100] opened 2015-04-14 00:28 UTC
```sass
linear-gradient(top, $header-button-background-color, adjust-color($header-button-background-color, $hue: -6deg, $lightness: -16, $saturation: -7));
```

Assuming $header-button-background-color is set to `#ffffff`, then I expect the above `adjust-color()` call to return `#d6d6d6` but it doesn't. It still returns the same, `#ffffff`. A bug? Or am I doing something wrong?

And yes, here the version I use (from gulp-sass within)

```
$ ./node-sass --version
2.1.1
```

**Comment by xzyfer** [comment] 2015-04-14 00:36
I've boiled down your example to executable Sass.

```scss
$foo: #ffffff;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

Give this the output is as expected

```css
foo {
  bar: #d3d9d8; }
```

You can confirm this behaviour yourself on sassmeister - http://sassmeister.com/gist/66b7f11f8e72e620d85c

Node-sass 2.1.1 is using Libsass 3.1.0 which is the same as sassmeister (click the cog in the top right for more info) - https://github.com/sass/node-sass/blob/226861c6a186291f9e957697f1115e1ddb4a4202/package.json#L3-L4

***

I am currently unable to reproduce this issue. Can you please create an executable example that shows this issue in action on sassmeister? Without that we simply cannot make progress here.

**Comment by binarykitchen** [comment] 2015-04-14 01:34
Ah, thanks for your work. After some debugging I found out that `$header-button-background-color` was set to `white` and that didn't work. But when I set that variable to `#fff`, then it worked. Weird.

**Comment by xzyfer** [comment] 2015-04-14 01:40
Interesting, `white` is still a valid value for `adjust-color()`.

```scss
$foo: white;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

Ruby Sass
```css
foo {
  bar: #d6d6d6; }
```

Libsass
```css
foo {
  bar: #d3d9d8; }
```

*** 
There does however appear to be a difference in how we calculate the adjusted colour.

**Comment by binarykitchen** [comment] 2015-04-14 01:49
Ouch!

**Comment by xzyfer** [comment] 2015-04-14 01:51
I would still like to get to the bottom of your issue.

**Comment by binarykitchen** [comment] 2015-04-14 01:52
If you want to reproduce it, then try using gulp-sass and compile

```sass
$foo: white;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

**Comment by xzyfer** [comment] 2015-04-14 01:53
Tracking the difference in `adjust-color()` in https://github.com/sass/libsass/issues/1101

**Comment by xzyfer** [comment] 2015-04-14 02:01
Running via node-sass@3.0.0-beta.5 and node-sass@2.1.1 produce the following output

```
foo {\n  bar: #d3d9d8; }\n
```

What version of gulp-sass are you using?

**Comment by binarykitchen** [comment] 2015-04-14 02:04
gulp-sass v1.3.3 (it is the latest)

**Comment by mgreter** [comment] 2015-05-08 00:46
This seems to be fixed on latest master (tested @xzyfer example) -> https://github.com/sass/libsass/commit/79e8d32e05f8b6fce0dc60c62f6b8cabcc8dc92b!

**Closed by mgreter** 2015-05-08 00:46 UTC
Labels: clarify

**Comment by binarykitchen** [comment] 2015-05-08 01:02
thx. let me know when it's published on npm

**Comment by xzyfer** [comment] 2015-05-08 03:37
Install gulp-sass@^2 to get this fix.
