### ISSUE TITLE
@extend circular references causes a Segmentation Fault

### ISSUE THREAD

**Issue by humphrey** [sass/libsass#1946] opened 2016-03-17 04:38 UTC
This code throws a Segmentation Fault.  I'm assuming it's called by a circular reference.

    .example-class {
      &.nav-justified {
        @extend .nav-justified;
      }
    }

**Comment by humphrey** [comment] 2016-03-17 05:12
!!! uWSGI process 23679 got Segmentation Fault !!!
    *** backtrace of 23679 ***
    /usr/local/bin/uwsgi(uwsgi_backtrace+0x2e) [0x4696ee]
    /usr/local/bin/uwsgi(uwsgi_segfault+0x21) [0x469ab1]
    /lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7ff2d80afd40]
    /opt/venv/polygon/local/lib/python2.7/site-    packages/_sass.so(_ZN4Sass6ExtendclEPNS_5BlockE+0xf5) [0x7ff2d0a88b55]
    /opt/venv/polygon/local/lib/python2.7/site-packages/_sass.so(_ZN4Sass7Context7compileEv+0x30b) [0x7ff2d0a030fb]
    /opt/venv/polygon/local/lib/python2.7/site-packages/_sass.so(_ZN4Sass12File_Context5parseEv+0x2f2) [0x7ff2d09fec92]
    /opt/venv/polygon/local/lib/python2.7/site-packages/_sass.so(sass_compiler_parse+0xcc) [0x7ff2d09f28cc]
    /opt/venv/polygon/local/lib/python2.7/site-packages/_sass.so(sass_compile_file_context+0x6d) [0x7ff2d09f2fbd]
    /opt/venv/polygon/local/lib/python2.7/site-packages/_sass.so(+0x960bb) [0x7ff2d09b40bb]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4bd4) [0x7ff2d85cc0d4]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7ff2d85cd54d]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x48d8) [0x7ff2d85cbdd8]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7ff2d85cd54d]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x48d8) [0x7ff2d85cbdd8]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7ff2d85cd54d]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1c37a5) [0x7ff2d86027a5]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7ff2d856ed43]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0xeb1) [0x7ff2d85c83b1]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4b59) [0x7ff2d85cc059]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7ff2d85cd54d]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1c37a5) [0x7ff2d86027a5]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7ff2d856ed43]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0xeb1) [0x7ff2d85c83b1]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4b59) [0x7ff2d85cc059]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4b59) [0x7ff2d85cc059]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7ff2d85cd54d]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1c36d0) [0x7ff2d86026d0]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7ff2d856ed43]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0xbb7bd) [0x7ff2d84fa7bd]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7ff2d856ed43]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7ff2d85e7577]
    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x110f92) [0x7ff2d854ff92]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7ff2d9a6c182]
    /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff2d817400d]
    *** end of backtrace ***

**Comment by xzyfer** [comment] 2016-03-17 11:37
Thanks for the report @humphrey. This is a duplicate of #1916.

**Closed by xzyfer** 2016-03-17 11:37 UTC
