### ISSUE TITLE
env() breaks libsass

### ISSUE THREAD

**Issue by danwood** [sass/libsass#2521] opened 2018-01-02 00:43 UTC
Libsass doesn’t understand [the new “env” that Apple has introduced into the syntax.](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)

```
/* Use @supports per https://webkit.org/blog/7929/designing-websites-for-iphone-x/ */
@supports(padding: max(0px)) {
    .post {
        padding-left: max(1em, env(safe-area-inset-left));
        padding-right: max(1em, env(safe-area-inset-right));
    }
}
```
## Actual results

```
Libsass: Error: "env(safe-area-inset-left)" is not a number for `max'
      on line 231 of /path/to/css/main.scss
      padding-left: max(1em, env(safe-area-inset-left));
 ----------------------^

```
## Expected result

There should be no error.

version info:

Sass 3.5.1 (Bleeding Edge)

**Comment by mgreter** [comment] 2018-01-11 05:08
IMO this is also not supported by ruby sass, tested with Sass 3.5.5 (Bleeding Edge).
```
Error: "env(safe-area-inset-left)" is not a number for `max'
```

**Comment by mgreter** [comment] 2018-01-11 21:41
This should probably be reported upstream //CC @nex3 @chriseppstein

**Comment by nex3** [comment] 2018-01-12 21:55
This is a duplicate of https://github.com/sass/sass/issues/2378. The issue here isn't really `env()`, it's that CSS introduced `max()` and `min()` functions that work very differently than the existing Sass functions with the same names.

**Closed by nex3** 2018-01-12 21:55 UTC
Labels: Invalid - Not in Sass
