### ISSUE TITLE
Problem with @at-root and extending

### ISSUE THREAD

**Issue by lmartins** [sass/libsass#1429] opened 2015-08-05 09:28 UTC
Hi, im having a problem which I believe is related to Libsass.
Im using the eq.js library, which declares a mixin making use of @at-root and extending features. The code for that can be viewed at:
https://github.com/Snugug/eq.js/blob/1.x.x/sass/_eq.scss#L25-L47

This mixin is used like this:

```scss
.loop--list{

    @include eq("large") {
        border: 1px solid red;
    }
```

Which is expected to output something like:
```css
.loop--list[data-eq-state$='"large"'] {
    border: 1px solid red
}
```

What happens instead is this:
```css
.loop--list .loop--list[data-eq-state$='"large"'] {
    border: 1px solid red
}
```

Thanks.

**Comment by xzyfer** [comment] 2015-08-10 01:29
Please produce a copy pastable working code. We don't have to dig around into other people's libraries.

I believe this is likely a duplicate of https://github.com/sass/libsass/issues/1297 and will be fixed by next LibSass release.

**Comment by mgreter** [comment] 2015-08-30 00:19
Closing because there is not enough information here to proceed.
Please re-open once you can provide working sample code. Thank you!

**Closed by mgreter** 2015-08-30 00:19 UTC
Labels: Bug - Maybe
