### ISSUE TITLE
Problems with nth-child

### ISSUE THREAD

**Issue by corysimmons** [sass/libsass#1048] opened 2015-04-06 08:05 UTC
https://github.com/corysimmons/lost/issues/52#issuecomment-89916443

Anyone care to look into this and give me an update on the status? Thanks

**Comment by xzyfer** [comment] 2015-04-06 11:48
Hi @corysimmons 

We're not familiar with lost, please provided sample input and expected output that produces the broken behaviour .

**Comment by Panya** [comment] 2015-04-06 12:46
Looks like duplicate of #593

**Comment by xzyfer** [comment] 2015-04-06 13:13
This issued linked to seems to suggest the `nth-child()` clause is being changed

>libass:
>```
>figure:nth-child(n)
>...
>figure:nth-child(n+1)
>```
>vs.
>
>CodePen:
>```
>figure:nth-child(2n)
>...
>figure:nth-child(2n + 1)
>```

Without knowing the coded used to generate the above output we cannot progress this issue.

Thank you @Panya but this is not related #593 which is only related to whitespace being lost.

**Comment by corysimmons** [comment] 2015-04-06 20:16
I use a [split string function](https://github.com/corysimmons/lost/blob/master/scss/lost.scss#L200) to [grab the denominator](https://github.com/corysimmons/lost/blob/master/scss/lost.scss#L250) from this stringed fraction and set it to `$cycle`.

Then I use `&:nth-child(#{$cycle}n) { ... }` to perform [some operations](https://github.com/corysimmons/lost/blob/master/scss/lost.scss#L310) on every nth-child.

This works on other versions of SCSS including CodePen but doesn't work with LibSass. Thank you.

**Comment by xzyfer** [comment] 2015-04-07 00:17
Thanks @corysimmons. Please provide a fully working (copy-pastable) code sample that produces the problem? sassmeister.com is very helpful for this.

**Comment by corysimmons** [comment] 2015-04-07 00:28
@xzyfer Apparently it's the `sl-explode()` function.

http://sassmeister.com/gist/1f0fecbb6af5ca3d2f3b

**Comment by xzyfer** [comment] 2015-04-07 00:34
Thanks @corysimmons. I can confirm this is fixed in 3.2.0-beta.5. My guess is it was related to some `str-slice` issues we had.

![screen shot 2015-04-07 at 10 32 57 am](https://cloud.githubusercontent.com/assets/579928/7015099/90fef532-dd11-11e4-9458-05ad90f0e475.png)

**Closed by xzyfer** 2015-04-07 00:34 UTC

**Comment by corysimmons** [comment] 2015-04-07 01:08
Neat, eta on 3.2.0?

**Comment by xzyfer** [comment] 2015-04-07 02:07
It's currently in it's second RC. We've noticed some sourcemaps issues, but otherwise things are looking good. We'll hopefully in the coming week or two.

**Comment by xzyfer** [comment] 2015-04-07 02:08
You can follow the [3.2 milestone](https://github.com/sass/libsass/milestones/3.2)

**Comment by corysimmons** [comment] 2015-04-07 02:41
@xzyfer Awesome, thanks for answering my questions. Have a nice day!
