### ISSUE TITLE
"Incompatible units" when using min() function with vh and px

### ISSUE THREAD

**Issue by tkondrashov** [sass/libsass#3061] opened 2020-02-12 21:05 UTC
## input.scss

```scss
.App {
  font-size: min(5.5vh, 30px);
}
```

## Actual results

[libsass 3.5.4][1]
```Failed to compile.
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)
SassError: Internal Error: Incompatible units: 'px' and 'vh'.
```

## Expected result

```css
.App {
  font-size: min(5.5vh, 30px);
}
```

version info:
```cmd
$ node-sass -v
node-sass	4.13.1	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#Ci5BcHAgewogIGZvbnQtc2l6ZTogbWluKDUuNXZoLCAzMHB4KTsKfQ==

**Comment by nex3** [comment] 2020-02-12 21:43
Duplicate of #2701. See the compatibility notes for `min()` and `max()` in [the Sass documentation](https://sass-lang.com/documentation/syntax/special-functions#min-and-max).

**Closed by nex3** 2020-02-12 21:43 UTC

**Comment by tkondrashov** [comment] 2020-02-12 23:57
> Duplicate of #2701. See the compatibility notes for `min()` and `max()` in [the Sass documentation](https://sass-lang.com/documentation/syntax/special-functions#min-and-max).

The documentation appears to be wrong - this is an example where `valid plain CSS` does not get compiled to a CSS min() call. I think this is a separate issue from supporting min or max in general, as it's a bug with that functionality.
