### ISSUE TITLE
@extend with wrapped selectors has combinatorial explosion of selectors

### ISSUE THREAD

**Issue by uberska** [sass/libsass#2399] opened 2017-05-22 15:35 UTC
### @extend with wrapped selectors has combinatorial explosion of selectors

input.scss
```scss
.thing {
	color: black;
}

.a,
.b,
.c,
.d,
.e {
	&:not(.thing) { @extend .thing; }
}
```

libsass 3.5.0.beta.3-20-g9eb7b333 via SourceMap Inspector [1]
```css
.thing, .a:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))),
.b:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)) {
  color: black; }
```

ruby sass 3.4.21 via SassMeister
```css
.thing, .a:not(.thing),
.b:not(.thing),
.c:not(.thing),
.d:not(.thing),
.e:not(.thing) {
  color: black;
}
```

[1]: http://libsass.ocbnet.ch/srcmap/#LnRoaW5nIHsKCWNvbG9yOiBibGFjazsKfQoKLmEsCi5iLAouYywKLmQsCi5lIHsKCSY6bm90KC50aGluZykgeyBAZXh0ZW5kIC50aGluZzsgfQp9Cg==

**Comment by mgreter** [comment] 2017-05-22 15:40
This seems to be a duplicate of https://github.com/sass/libsass/issues/2055

**Comment by uberska** [comment] 2017-05-22 16:31
Thanks for the quick comment! I saw that issue, but didn't realize it was the same thing.

We're trying to update our codebase from 3.0 -> 3.5.0.beta3. This issue causes quite a bit of bloat in our css. Where I have .a through .e in the example, we actually have 16 selectors.

From some of the other issues I found through the link you provided, it sounds like support for extending wrapped selectors isn't fully supported yet. Given that we're coming from 3.0 and haven't had extend for wrapped selectors yet, one outcome that could be useful for us would be to turn it off until the implementation is fully supported. Would you accept a pull request in libsass and node-sass for a flag to disable extends on wrapped selectors?

**Comment by mgreter** [comment] 2017-05-22 16:41
No, because basic stuff works and we don't want to break that. Maybe if specifically targeting `:not`, but I think a correct patch would be hard to come up. As it is difficult to get correct `:not` extend behavior. I guess you might be better off with some specific post-processing in this case, if the bloat really bothers you. Not even sure why you would want to disable that feature, couldn't you just remove the line in scss then? Of course we always welcome PRs that improve libsass and do not break any existing spec tests.

**Comment by mgreter** [comment] 2017-05-22 18:29
Took me 2 hours to come up with a hotfix to at least hide nested `:not` selectors. This will probably cover about 70% of real world use cases (including this one) and should not give any "wrong negatives". Will take me some moments to create needed spec test and PR ...

**Closed** 2017-05-22 19:04 UTC
Labels: Bug - Confirmed, Dev - Test Written, Dev - WIP, Invalid - Duplicate

**Comment by uberska** [comment] 2017-05-22 19:46
Wow, thanks for the quick turnaround, @mgreter ! We'll try a new build with libsass master.

**Comment by uberska** [comment] 2017-05-30 13:16
With master, our problem seems to be fixed. Thanks @mgreter !

**Comment by mgreter** [comment] 2017-05-30 14:38
Cool, great, thanks for the feedback!

**Comment by marticongost** [comment] 2017-07-04 15:12
I have noticed a regression on 0.13 that I suspect may be related to this change.

This is the SASS source:
```
#searchForm {
    flex: 1 1 auto;

    :host(:not([searchEnabled='true'])) & {
        display: none;
    }
}
```

In 0.12, the inner selector produced the following CSS:
```
#searchForm {
  flex: 1 1 auto; }
  :host(:not([searchEnabled='true'])) #searchForm {
    display: none; }
```

Whereas on 0.13 I get this:
```
#searchForm {
  flex: 1 1 auto; }
   #searchForm {
    display: none; }
```

If I remove the :not() selector from the original source, 0.13 produces the following rules, which is the expected result:

#searchForm {
  flex: 1 1 auto; }
  :host([searchEnabled='true']) #searchForm {
    display: none; }

**Comment by mgreter** [comment] 2017-07-04 15:34
@marticongost this is not reproducable with [latest master][1] and gives your expected result.

[1]: http://libsass.ocbnet.ch/srcmap/#I3NlYXJjaEZvcm0gewogIGZsZXg6IDEgMSBhdXRvOyB9CiAgOmhvc3QoOm5vdChbc2VhcmNoRW5hYmxlZD0ndHJ1ZSddKSkgI3NlYXJjaEZvcm0gewogICAgZGlzcGxheTogbm9uZTsgfQ==

**Comment by marticongost** [comment] 2017-07-04 16:10
The online tool seems to be using 3.5b. Could this have been fixed by a later change in master (https://github.com/sass/libsass/commit/5a7dbc80a9f6b8062006b758d05bb302a695cc1f)? I can certainly reproduce it in 3.4.5. I'm using the Python bindings.
