### ISSUE TITLE
Unexpected behaviour with @at-root

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1236] opened 2015-05-25 14:09 UTC
Bug found by Jaime Caballero: https://twitter.com/jaicab_/status/602583391515574273.

## Test case

```scss
@mixin test {
  $selector-list: &;                 // (.a .b,)
  $selector: nth($selector-list, 1); // (.a .b)
  $first: nth($selector, 1);         // .a
  $second: nth($selector, 2);        // .b
  $add: 'dummy';
  
  @at-root #{$first} #{$add} #{$second} {
    @content;
  }
}


.a .b {
  @include test {
    color: red;
  }
}
```

## Expected result

```css
.a dummy .b {
  color: red;
}
```

## Actual result (LibSass 3.2.4)

```css
.a .b .a dummy .b {
  color: red;
}
```

**Comment by jaicab** [comment] 2015-05-25 23:17
Thanks @HugoGiraudel for setting up this issue!
It's interesting that when you add some actual text around it (like an `html` tag or something) it does work. Check out my original [example on SassMeister] (http://sassmeister.com/gist/16f04ff12d551b551902).

**Comment by xzyfer** [comment] 2015-05-27 23:10
I've assigned this to 3.3. A spec would be appreciated. Possibly related to https://github.com/sass/libsass/issues/1210

**Comment by HugoGiraudel** [comment] 2015-05-28 07:28
Ping @xzyfer How would you name this?

**Comment by HugoGiraudel** [comment] 2015-05-28 07:34
There you have it.

**Comment by mgreter** [comment] 2015-05-30 00:26
This issue is also covered by my latest WIP branch, which seems to fix most if not all `@at-root` related bugs (ETA unknown, targeted 3.3): https://github.com/sass/libsass/pull/1249

**Comment by xzyfer** [comment] 2015-05-31 00:55
Looking at this closer it's actually just an @at-root problem. The selector functions have nothing to do with.

This is a duplicate of https://github.com/sass/libsass/issues/1210.

**Closed by xzyfer** 2015-05-31 00:55 UTC
Labels: bug, needs test, WIP
