### ISSUE TITLE
Compile fails on Joyent SmartOS

### ISSUE THREAD

**Issue by brentjohnson** [sass/libsass#850] opened 2015-01-21 15:31 UTC
This compile error happens when attepmting to install via:  "npm install grunt-sass"

  CXX(target) Release/obj.target/binding/src/libsass/json.o
../src/libsass/json.cpp:159:18: error: conflicting declaration 'typedef uint32_t uchar_t'
In file included from /usr/include/sys/wait.h:38:0,
                 from /usr/include/stdlib.h:36,
                 from ../src/libsass/json.cpp:29:
/usr/include/sys/types.h:98:23: error: 'uchar_t' has a previous declaration as 'typedef unsigned char uchar_t'
../src/libsass/json.cpp: In function 'int utf8_write_char(uchar_t, char*)':
../src/libsass/json.cpp:299:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:299:3: warning: comparison is always false due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:299:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:305:25: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:310:25: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp: In function 'void to_surrogate_pair(uchar_t, uint16_t*, uint16_t*)':
../src/libsass/json.cpp:351:3: warning: comparison is always false due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:351:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp: In function 'void emit_string(SB*, const char*)':
../src/libsass/json.cpp:1214:42: error: cannot convert 'uint32_t* {aka unsigned int*}' to 'uchar_t* {aka unsigned char*}' for argument '2' to 'int utf8_read_char(const char*, uchar_t*)'
make: *** [Release/obj.target/binding/src/libsass/json.o] Error 1

**Comment by mgreter** [comment] 2015-01-31 04:02
We need at least OS and Compiler version!

**Comment by brentjohnson** [comment] 2015-02-03 21:53
$ gcc -v
gcc version 4.7.2 (GCC)
Target: x86_64-sun-solaris2.11

$ uname -irsv
SunOS 5.11 joyent_20130808T165657Z i86pc

**Comment by xzyfer** [comment] 2015-02-03 22:23
Can you please produce the entire output generated by `npm install --verbose node-sass`?

**Comment by nielsgoossens** [comment] 2015-04-04 00:09
Was this issue ever resolved? I am witnessing the same problem.

gcc (GCC) 4.9.1, SunOS 5.11 joyent_20141212T011737Z i86pc

../src/libsass/json.cpp:159:18: error: conflicting declaration 'typedef uint32_t uchar_t'
 typedef uint32_t uchar_t;
                  ^
In file included from /usr/include/sys/wait.h:37:0,
                 from /usr/include/stdlib.h:41,
                 from ../src/libsass/json.cpp:29:
/usr/include/sys/types.h:98:23: note: previous declaration as 'typedef unsigned char uchar_t'
 typedef unsigned char uchar_t;
                       ^
In file included from ../src/libsass/json.cpp:26:0:
../src/libsass/json.cpp: In function 'int utf8_write_char(uchar_t, char*)':
../src/libsass/json.cpp:299:18: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   assert(unicode <= 0x10FFFF && !(unicode >= 0xD800 && unicode <= 0xDFFF));
                  ^
../src/libsass/json.cpp:299:43: warning: comparison is always false due to limited range of data type [-Wtype-limits]
   assert(unicode <= 0x10FFFF && !(unicode >= 0xD800 && unicode <= 0xDFFF));
                                           ^
../src/libsass/json.cpp:299:64: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   assert(unicode <= 0x10FFFF && !(unicode >= 0xD800 && unicode <= 0xDFFF));
                                                                ^
../src/libsass/json.cpp:305:22: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   } else if (unicode <= 0x7FF) {
                      ^
../src/libsass/json.cpp:310:22: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   } else if (unicode <= 0xFFFF) {
                      ^
In file included from ../src/libsass/json.cpp:26:0:
../src/libsass/json.cpp: In function 'void to_surrogate_pair(uchar_t, uint16_t*, uint16_t*)':
../src/libsass/json.cpp:351:18: warning: comparison is always false due to limited range of data type [-Wtype-limits]
   assert(unicode >= 0x10000 && unicode <= 0x10FFFF);
                  ^
../src/libsass/json.cpp:351:40: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   assert(unicode >= 0x10000 && unicode <= 0x10FFFF);
                                        ^
../src/libsass/json.cpp: In function 'void emit_string(SB*, const char*)':
../src/libsass/json.cpp:1214:42: error: cannot convert 'uint32_t* {aka unsigned int*}' to 'uchar_t* {aka unsigned char*}' for argument '2' to 'int utf8_read_char(const char*, uchar_t*)'
           s += utf8_read_char(s, &unicode);
                                          ^
binding.target.mk:128: recipe for target 'Release/obj.target/binding/src/libsass/json.o' failed
make: *** [Release/obj.target/binding/src/libsass/json.o] Error 1
make: Leaving directory '/opt/ghost/content/themes/Decode-for-Ghost-master/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/ghost/content/themes/Decode-for-Ghost-master/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/opt/local/bin/node" "/opt/ghost/content/themes/Decode-for-Ghost-master/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/ghost/content/themes/Decode-for-Ghost-master/node_modules/node-sass
gyp ERR! node -v v0.10.33
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
Build failed

**Comment by mgreter** [comment] 2015-04-04 01:30
From the output, this looks like a downstream error. Please only report build problems to libsass that are directly related to the build system supported by libsass. So please try to reproduce with the official libsass build, or report to node-sass (they might already be aware of this issue)!

**Comment by Candid** [comment] 2015-04-10 23:29
I don't think it's "downstream" error. I get this error on SmartOS when I run `make` inside `libsass` directory:
```
g++ -Wall -O2 -DLIBSASS_VERSION="\"3.2.0-beta.5-16-ge60a\"" -std=c++0x -I /root/libsass/ -fPIC -c -o json.o json.cpp
json.cpp:159:18: error: conflicting declaration 'typedef uint32_t uchar_t'
In file included from /usr/include/sys/wait.h:38:0,
                 from /usr/include/stdlib.h:40,
                 from json.cpp:29:
/usr/include/sys/types.h:98:23: error: 'uchar_t' has a previous declaration as 'typedef unsigned char uchar_t'
json.cpp: In function 'void emit_string(SB*, const char*)':
json.cpp:1214:42: error: cannot convert 'uint32_t* {aka unsigned int*}' to 'uchar_t* {aka unsigned char*}' for argument '2' to 'int utf8_read_char(const char*, uchar_t*)'
Makefile:210: recipe for target 'json.o' failed
make: *** [json.o] Error 1
```
(gcc 4.7.3, SunOS 5.11 joyent_20131227T234851Z i86pc i386 i86pc Solaris)

**Comment by xzyfer** [comment] 2015-04-13 13:38
@mgreter this appears to be an issue with our json library as per https://github.com/sass/libsass/pull/1094

**Comment by mgreter** [comment] 2015-04-13 16:17
IMO from the error it seems like a `#ifndef` around these `uchar_t` typedef declaration should fix it too?

**Comment by Candid** [comment] 2015-04-13 16:31
@mgreter `json.cpp` requires `uchar_t` to be 32 bit. The definition in `types.h` makes it 8 bit. So no, `#ifndef` won't fix the issue.

**Comment by saper** [comment] 2015-04-13 19:53
Pushed @Candid 's version with `uint32_t` as #1099

**Closed** 2015-04-14 01:05 UTC
Labels: clarify

**Comment by xzyfer** [comment] 2015-04-14 01:07
Thanks @Candid and @saper for your work!

I merged @saper's because I thought there was value in keeping [this comment](https://github.com/sass/libsass/pull/1099/files#diff-45e24f5c6f05002852129e4efec4b369R154), and since he rebased @Candid commit your both credited with the contribution.

**Comment by saper** [comment] 2015-04-15 21:34
@djensen47 suggests in https://github.com/sass/node-sass/issues/858#issuecomment-93570201 to apply this to 3.1.0 (and release 3.1.1) The actual `json.cpp` is the same on 3.1.x and 3.2.x so the patch can be just cherry-picked.

**Comment by xzyfer** [comment] 2015-04-15 23:57
Unfortunately Libsass isn't currently managed in a way that would make back porting patches possible without some major kludging. However we're about to release a new beta which will include this patch. I'll then promptly update node-sass.

We'll aim to address our process post 3.2.0 as per https://github.com/sass/libsass/issues/796

**Comment by djensen47** [comment] 2015-04-16 00:05
:ok_hand: :+1:

**Comment by djensen47** [comment] 2015-07-06 17:29
It appears that libsass is failing to compile again …

```
$ sudo npm install -g node-sass
/opt/local/bin/node-sass -> /opt/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.2.0 install /opt/local/lib/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/sunos-x64-14_binding.node": HTTP error 404 Not Found

> node-sass@3.2.0 postinstall /opt/local/lib/node_modules/node-sass
> node scripts/build.js

Building: /opt/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/local/lib/node_modules/node-sass/.node-gyp"
make: Entering directory '/opt/local/lib/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
In file included from ../src/libsass/ast.hpp:34:0,
                 from ../src/libsass/ast.cpp:1:
../src/libsass/units.hpp:39:5: error: expected identifier before numeric constant
../src/libsass/units.hpp:39:5: error: expected '}' before numeric constant
../src/libsass/units.hpp:39:5: error: expected unqualified-id before numeric constant
../src/libsass/units.hpp:62:3: error: 'SassUnit' does not name a type
../src/libsass/units.hpp:63:30: error: 'SassUnit' was not declared in this scope
../src/libsass/units.hpp:63:30: note: suggested alternative:
../src/libsass/units.hpp:22:8: note:   'Sass::SassUnit'
../src/libsass/units.hpp:64:3: error: 'SassUnitType' does not name a type
../src/libsass/units.hpp:66:34: error: 'string' does not name a type
../src/libsass/units.hpp:66:40: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:66:49: error: 'string' does not name a type
../src/libsass/units.hpp:66:55: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:69:3: error: expected class-name before '{' token
../src/libsass/units.hpp:72:34: error: expected ')' before 'a'
../src/libsass/units.hpp:87:1: error: expected declaration before '}' token
src/libsass.target.mk:128: recipe for target 'Release/obj.target/libsass/src/libsass/ast.o' failed
make: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
make: Leaving directory '/opt/local/lib/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/local/lib/node_modules/node-sass
gyp ERR! node -v v0.12.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
npm ERR! SunOS 5.11
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "-g" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by saper** [comment] 2015-07-06 18:25
@djensen47: Can you (1) open another bug for this, (2) provide your compiler details (3) try to compile with `env V=1 npm install node-sass`?

**Comment by djensen47** [comment] 2015-07-06 18:39
I opened a bug on libsass. I'll open another one here.
