### ISSUE TITLE
sassc using large amount of memory with libsass 3.6.3

### ISSUE THREAD

**Issue by phmccarty** [sass/libsass#3033] opened 2019-11-05 20:04 UTC
I am attempting to build the latest release of [arc-theme](https://github.com/arc-design/arc-theme), which has a build dependency on sassc/libsass.

With libsass 3.6.2, the build was hanging, very likely due to [this issue](https://github.com/sass/libsass/issues/3006). With libsass 3.6.3, sassc starts to consume large amounts of memory. I don't know if the build would successfully complete, because my system was about to run out of memory; sassc was using about 14 GB of RAM when I killed the process.

Steps to reproduce:

```
git clone https://github.com/arc-design/arc-theme
cd arc-theme/common/gtk-3.0/3.20
sassc sass/gtk.scss gtk.css
```

**Comment by saper** [comment] 2019-11-06 01:06
node-sass using libsass 3.5.5 compiled it under 2 seconds:

````
> time node-sass sass/gtk.scss sass/gtk.css
Rendering Complete, saving .css file...
Wrote CSS to /home/saper/sw/arc-theme/common/gtk-3.0/3.20/sass/gtk.css

real    0m2,02s
user    0m1,60s
sys     0m0,19s
````

**Comment by saper** [comment] 2019-11-06 02:06
With libsass master (d91105 which is 3.6.3 plus 4 commit) there are lots of warnings:

    Compound selectors may no longer be extended.

**Comment by xzyfer** [comment] 2019-11-06 02:41
This is a deprecation notice we introduced.

**Comment by saper** [comment] 2019-11-06 03:18
@xzyfer but is this feature still supported? it seems that extension process is causing trouble here (according to the debugger)

**Comment by mgreter** [comment] 2019-11-06 10:29
Has anyone tried it with dart sass, I suspect it will run into the same issue.

**Comment by mgreter** [comment] 2019-11-06 10:32
AFAIR that gtk theme has quite a few `@extend *` which seems to cause long runtime.

**Comment by saper** [comment] 2019-11-06 10:32
Nope, dart is not even [running on my system](https://github.com/dart-lang/sdk/issues/10260#issuecomment-372138711).

**Comment by saper** [comment] 2019-11-06 10:38
Does it ever finish? I poked around it with a debugger and it seems to jump around extending stuff; it also does not seem to endlessly recurse.

**Comment by mgreter** [comment] 2019-11-06 20:56
I believe it will finish if you have an absurd amount of RAM. It seems to even exhaust 64GB. But the real issue is that the extend rules for this theme are really getting out of hand and probably don't work as they have been intended. Not sure exactly how or why older libsass extend was working but I suspect that we didn't obey the 3rd law of extend (It trims redundant selectors as much as possible, while still ensuring that the specificity is greater than or equal to that of the extender). Dart-sass seems to behave exactly the same, albeit slower accumulating memory.

FWIW I was able to compile `_common.scss` and it alone produced a 6MB big css file. 

![image](https://user-images.githubusercontent.com/282293/68336862-95d9b000-00df-11ea-88c1-c88da39a1dd0.png)

**Comment by lazka** [comment] 2019-11-08 17:01
Same problem with the default gtk CSS theme: https://gitlab.gnome.org/GNOME/gtk/issues/2237

sassc used to create a 192kb CSS file and starting with 3.6.3 (3.6.2 didn't build at all) the resulting CSS is 70MB large.

**Comment by mgreter** [comment] 2019-11-09 15:29
It seems to boil down to some usage pattern like these:
```scss
%undecorated_button {
  box-shadow: none;
}

button:link:hover, button:visited:hover,
button:link:active, button:visited:active,
button:link:checked, button:visited:checked {
  @extend %undecorated_button;
}

headerbar {
  @extend %header_widgets;
}

%header_widgets {

  &.selection-mode button {

    &, &.flat {
      asd: qwe;
    }
    &:active, &:checked { @extend :active; }

    &:disabled {
      @extend :disabled;

      &:checked, &:active { @extend :disabled, :checked; }
    }
  }
}
```

I would suggest to take this upstream to dart-sass, as it suffers from the same issue.

**Comment by lazka** [comment] 2019-11-10 21:36
Here is an example which produces a bogus result starting with 3.6.2:

```scss
*:hover {
  *:visited {
    color: green;
  }
}

button {
  @extend *:hover;
}
```

**Comment by saper** [comment] 2019-11-10 22:41
Is there a relatively current sass language specification? I think we have reached the point here where just following the reference implementation leads to wrong results.

**Comment by nex3** [comment] 2019-11-12 00:10
@saper There's a partial spec in https://github.com/sass/sass/tree/master/spec. It gets filled in lazily as necessary when writing proposals for new language features.

**Comment by bdkjones** [comment] 2019-11-25 17:20
Is there a proposed resolution for this? I shipped Libsass 3.6.2 but had to rollback after many reports of hung compiling. It seems this issue is likely to affect many people, so I’m hesitant to ship 3.6.3 now.

**Comment by mgreter** [comment] 2019-11-26 14:05
No, there hasn't, but the hung compilation was another issue that should be addressed correctly in 3.6.3. The issue here is how the exend logic of dart sass works. I think if you don't use `extend *` it should be safe (and I think one really shouldn't use that pattern). Any chance you can put out a beta version for further testing?

**Comment by q66** [comment] 2019-12-16 12:21
I can confirm that 3.6.3 hangs and keeps eating memory until it invokes OOM killer. Void Linux `ppc64le`, trying to build `arc-theme`.

**Comment by mgreter** [comment] 2021-03-04 05:56
Closing this out as it is as it is. Since LibSass follows the lead of now official dart sass, and this same problem exists there, we can't do much to fix. This behavior is intrinsically related to how dart sass now handles `@extend` and any future LibSass release will suffer from this issue. If you believe this is wrong please take your arguments upstream to https://github.com/sass/sass. Please re-open with further info, if you find a case where dart-sass compiles OK but LibSass doesn't.

**Closed by mgreter** 2021-03-04 05:56 UTC
Labels: Bug - Maybe, Bug - Upstream
