### ISSUE TITLE
min & max functions removes first item from list 

### ISSUE THREAD

**Issue by sup3rman** [sass/libsass#824] opened 2015-01-07 18:00 UTC
I posted this as an issue on node-sass, but was told this was likely an error with libsass.

Since node-sass >= 1.1.X the min and max functions have begun to remove the first item when passed a list variable.

To reproduce:
```
$range: 1px, 2px, 3px, 4px;
@debug $range;//1px, 2px, 3px, 4px
$test: min($range...);
@debug $range;//2px, 3px, 4px
$test: max($range...);
@debug $range;//3px, 4px
$test: max($range...);
@debug $range;//4px
```

This is not the behaviour in Ruby's sass.

**Comment by xzyfer** [comment] 2015-01-07 22:02
This is a duplicate of https://github.com/sass/libsass/issues/813. Please follow the progress there.

**Closed by xzyfer** 2015-01-07 22:02 UTC
