### ISSUE TITLE
Compile libsass for iOS and Android as a static library.

### ISSUE THREAD

**Issue by jpdery** [sass/libsass#2710] opened 2018-08-09 12:39 UTC
I'm not sure if this is the right place to ask this, if not then I'm sorry. 

Long story short, I'm working on a mobile app platform and I'd like to use Sass for styling. I'm currently using Less because I found a C++ parser that can be slightly modified to give an AST which I can play with. 

However, being a Sass user, I'd rather use that. Now the question is, does anyone know if or how hard would it be to compile libsass for iOS and Android ? I know I would have to change bits and pieces of the code to use the AST (I think) but it would be very helpful to know if it can be done in the first place.

Thanks!

**Comment by mgreter** [comment] 2018-12-13 23:52
Closing as a duplicate of https://github.com/sass/libsass/issues/1065. We don't expose the AST since it is internal knowledge and subject of often subtle and rarely heavy changes. Therefore we are not willing yet to expose this to the outside. Hope I understood your question right, because simply compiling libsass alone on android or iOS should be or might be straight forward!

**Closed by mgreter** 2018-12-13 23:52 UTC
