### ISSUE TITLE
The unquote function is not consistent with Ruby Sass

### ISSUE THREAD

**Issue by trevorsg** [sass/libsass#2156] opened 2016-08-31 14:57 UTC
### Title: unquote("\"hello\" and \"goodbye\"") incorrectly strips the first and last quotes.

input.scss
```scss
@debug unquote("\"hello\" and \"goodbye\"");
```

[libsass] [1]
```css
DEBUG: hello" and "goodbye
```

ruby sass 3.4.19
```css
DEBUG: "hello" and "goodbye"
```

version info:
```cmd
$ sassc.exe --version
sassc: [NA] (master: 077af530)
libsass: [NA] (master: 014a61b6)
sass2scss: 1.0.6
sass: 3.4
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by mgreter** [comment] 2016-09-02 01:06
Seems to be a duplicate of https://github.com/sass/libsass/issues/2153

**Closed** 2016-09-02 06:34 UTC
Labels: Bug - Confirmed, Dev - Test Written
