### ISSUE TITLE
Error: expected a variable name (e.g. $x) or ')' for the parameter list for url

### ISSUE THREAD

**Issue by listepo** [sass/libsass#1097] opened 2015-04-13 15:05 UTC
For 3.2.0 beta 
```
File: bower_components/foundation/scss/foundation/components/_forms.scss (335)
expected a variable name (e.g. $x) or ')' for the parameter list for url
Error: expected a variable name (e.g. $x) or ')' for the parameter list for url
    at options.error (/Users/ivan/app/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:261:32)
```

**Comment by xzyfer** [comment] 2015-04-13 15:08
Sorry @listepo but this does not help us track down the bug. Please supply a set of copy paste instructions that reproduces this error. The latest foundation currently compiles fine with libsass@3.2.0-beta.5

**Comment by jrobeson** [comment] 2015-04-14 03:08
I can replicate the issue on node-sass 3.0.0-beta5  (which should use libsass 3.2.0-beta.5) . The node-sass folks suggest that it's fixed now though. https://github.com/sass/node-sass/issues/850

**Comment by jrobeson** [comment] 2015-04-14 03:18
this is the only stuff i currently have in my app.scss file.

```css
@import "settings";
@import "foundation";
@import "font-awesome";
@import "github";

.contact-info {
    list-style: none;
}
```

**Comment by xzyfer** [comment] 2015-04-14 03:33
Can you please show any other relevant package manager configs i.e. bower so we can replicate this issue. I don't know what `@import "github";` refers to, or what version of foundation and font-awesome you are using.

**Comment by jrobeson** [comment] 2015-04-14 03:39
ah truly. i meant to take github out, because it's just a css file (not sass/scss) and not relevant to replicating the issue. so pretend it doesn't exist (it's from the highlightjs package).

bower.json
```json
{
  "name": "site",
  "dependencies": {
    "foundation": "^5.0",
    "fontawesome": "latest",
    "jquery": "^2.0",
    "highlightjs": "^8.0"
  }
}
```

**Comment by xzyfer** [comment] 2015-04-14 03:59
Are you supplying a load path? i.e. how does sass know that `"foundation"` is infact `bower_components/foundation/scss/foundation.scss`?

What does `"settings"` point to? Is it relevant to this issue?

**Comment by xzyfer** [comment] 2015-04-14 04:06
Running this command with your bower settings on node-sass@2.1.1 produces no error

```
➜  issue_1097  ./node_modules/.bin/node-sass --version
2.1.1
➜  issue_1097  ./node_modules/.bin/node-sass --include-path bower_components/foundation/scss --include-path bower_components/fontawesome/scss index.scss
Rendering Complete, saving .css file...
Wrote CSS to /Users/michael/tmp/issue_1097/index.css
```

This suggests issue is in some customisation you have made.

**Comment by jrobeson** [comment] 2015-04-14 04:10
for some stupid reason i didn't even think about running it on the cli .. here we go:

node_modules/broccoli-sass/node_modules/.bin/node-sass -o build --include-path vendor/bower/foundation/scss --include-path vendor/bower/fontawesome/scss/ source/scss/app.scss 
{
  "message": "expected a variable name (e.g. $x) or ')' for the parameter list for url",
  "column": 24,
  "line": 335,
  "file": "vendor/bower/foundation/scss/foundation/components/_forms.scss",
  "status": 1

**Comment by jrobeson** [comment] 2015-04-14 04:12
i've made no customization to _settings.scss .. it's simply copied from foundation.. and showed the entire app.scss file i have. and i rm -rfed vendor/bower and reinstalled to make sure i had no customizations to anything in foundation.

**Comment by jrobeson** [comment] 2015-04-14 04:13
oh, also it doesn't occur if i switch out libsass for ruby sass.

**Comment by xzyfer** [comment] 2015-04-14 04:25
Ok great, I'm able reproduce this now :)

**Comment by xzyfer** [comment] 2015-04-14 04:50
OK I can confirm this is fix on master and will be in the next beta of Libsass and node-sass.

Thanks@jrobeson for your help!

**Closed by xzyfer** 2015-04-14 04:50 UTC
Labels: clarify

**Comment by jrobeson** [comment] 2015-04-14 04:56
YAY! . thank you too!

**Comment by mikeangstadt** [comment] 2015-04-21 16:17
Is this fixed yet?  Shouldn't you be waiting until it is available before closing an issue?

**Comment by mikeangstadt** [comment] 2015-04-21 16:18
" and will be in the next beta of Libsass and node-sass." where is a new node-sass build?

**Comment by xzyfer** [comment] 2015-04-22 00:05
The Libsass@3.0.0-beta.6 has already been released. The node-sass beta will follow shortly - https://github.com/sass/node-sass/issues/873

**Comment by perplexes** [comment] 2015-12-11 20:43
I'm running into this on current master (b2a3d98ed384d2d19aa79157d08fa21c3e8043e0): https://gist.github.com/perplexes/ff97bab5669b8dad0248

**Comment by xzyfer** [comment] 2015-12-27 07:01
@perplexes you code sample does not work with Ruby Sass. Please [open an issue](https://github.com/sass/sass/issues) with them if you believe this to be a mistake.

**Comment by volodos** [comment] 2016-01-25 12:27
I also have this error, i've done "npm install node-sass@beta" command, didn't worked.

The error is:  "Error: expected a variable name (e.g. $x) or ')' for the parameter list for alpha
        on line 112 of stdin"

Code:  input.File { width: 100%; position: relative; text-align: right; -moz-opacity: 0; filter: alpha(opacity: 0); opacity: 0; z-index: 30; cursor: pointer; }

**Comment by mgreter** [comment] 2016-01-25 13:25
@volodos Maybe try with the correct syntax. Yours doesn't compile in ruby sass either which you should always check before posting new issues. IE filter opacity alpha uses an equal sign, not a colon:
```css
input.File { width: 100%; position: relative; text-align: right; -moz-opacity: 0; filter: alpha(opacity=0); opacity: 0; z-index: 30; cursor: pointer; }
```
