### ISSUE TITLE
variables losing zeros

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1140] opened 2015-04-27 23:03 UTC
Sorry for the weird title, I'm not sure how to even describe this properly.

given the input

```scss
$line-height: 20px; div {line-height: $line-height;}
```

I get the output

```css
div {
  line-height: 2px; }
```

note how `20px` turned into `2px`. I see the same behavior for `0.1px` turning into `px`.

---

I've tracked the issue down to `sass_option_set_precision(ctx_opt, 0);` being the culprit. Not setting a precision, or setting any precision other than `0` works. I *think* I remember reading something about `0` being the libsass default. But I can't support that by linking to code. Judging from [sass_context.cpp](https://github.com/sass/libsass/blob/3.2.0/sass_context.cpp#L549) and [inspect.cpp](https://github.com/sass/libsass/blob/3.2.0/inspect.cpp#L420) I'd assume the default is `5`.

I'm not sure if this is an issue with code, the documentation, or me being daft (again).

**Comment by mgreter** [comment] 2015-04-27 23:43
Valid, see the same with perl-libsass:
```
# psass --precision 0 test.scss
div {
  line-height: 2px; }
# psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0
  sass2scss: 1.0.3
```

IMO it should be quite trivial to fix this "edge" case!
Got any expected behavior for negative precision :smile:  ?

**Comment by xzyfer** [comment] 2015-04-30 04:49
Fixed in [3.2.1](https://github.com/sass/libsass/releases/tag/3.2.1)

**Comment by rodneyrehm** [comment] 2015-04-30 08:02
Your fix may have gone a tiny bit too far. In 3.2.1 for `precision: 0`, the following code

```scss
$foo: 123px; .m { width: $foo; }
```

compiles to

```css
.m {
  width: 123.0px; }
```

I don't think adding `.0` is a good idea.

**Comment by xzyfer** [comment] 2015-04-30 08:09
Are right, yes that's a bug, but it doesn't change the semantic of the code which certainly an improvement.

**Comment by rodneyrehm** [comment] 2015-04-30 08:47
Oh, it even got worse:

```scss
$foo: 123.4px; .m { width: $foo; }
```

compiles to

```css
.m {
  width: 123.0px; }
```

so now we're actually losing precision

**Comment by xzyfer** [comment] 2015-04-30 12:34
@rodneyrehm I can't reproduce this with give code. Are you sure you're on 3.2.1?

```sh
$ sassc --precision=0 test.scss
.m {
  width: 123.0px; }
$ sass --precision=0 test.scss
.m {
  width: 123.0px; }
$ sassc --precision=5 test.scss
.m {
  width: 123.4px; }
$ sass --precision=5 test.scss
.m {
  width: 123.4px; }
```

**Comment by xzyfer** [comment] 2015-04-30 12:36
>I don't think adding .0 is a good idea.

Yes and no. Ruby Sass adds the `.0` if there would have otherwise been a decimal.

**Comment by rodneyrehm** [comment] 2015-04-30 12:41
I see your `sassc` vs `sass` test and realize that `precision:0` is *intended* to lose the decimal, it is *not* the value to set for "use libsass default"? If that's the case, what *is* the default value?

**Comment by xzyfer** [comment] 2015-04-30 12:50
`precision` sets the _maximum_ precision (number of digits after a decimal) to _truncate_ to i.e. `0.5` will not become `0.5000` when precision is 5.

If this what you desire there is no config or flag to achieve this.

**Comment by rodneyrehm** [comment] 2015-04-30 12:56
No, it's not what I desire. What I want is the ability to tell libsass to use its default value for precision. I assumed `0` would trigger that. Or maybe `-1` does. Or maybe nothing triggers the default value, in which case I'd like to know the default value, so I can set it instead of passing in `0`. If none of that is possible, I'll go and adjust my code to simply *not set precision*, in order to have libsass use its default value.

Maybe all of this is really just based on me not understanding that `precision:0` is *meant* to truncate the decimal part.

**Comment by mgreter** [comment] 2015-04-30 12:59
The default value is 5 (was changed some time ago from 3) and no, you cannot tell libsass to use the default again, since it is really on set when the context gets initialized (so you cannot "unsert" a config option currently, once it is set),

**Comment by xzyfer** [comment] 2015-04-30 13:02
As @mgreter said the default is 5 the same as Ruby Sass. We copy Ruby Sass where possible.

There is talk of this changing in the future though - https://github.com/sass/sass/issues/1122

**Comment by rodneyrehm** [comment] 2015-04-30 13:04
ok, preventing to set the precision seems like the easiest (and apparently future-proof) way. thanks!

**Comment by xzyfer** [comment] 2015-04-30 13:09
No problem. Apologies for the confusion. We're tracking the extra `.0` regression in https://github.com/sass/libsass/issues/1153

**Closed by xzyfer** 2015-04-30 13:09 UTC
Labels: bug

**Comment by rodneyrehm** [comment] 2015-04-30 13:12
No need to apologize, obviously I wasn't able to make clear what I wanted… 
Thanks guys! :)
