### ISSUE TITLE
`:not(selector)` is expanded incorrectly

### ISSUE THREAD

**Issue by calvin** [sass/libsass#1975] opened 2016-04-05 00:18 UTC
`&:not(selector)` is expanded to `&:not(selector, selector)`. Please see my input, actual output and expected output below. However, I cannot reproduce this problem on http://www.sassmeister.com.

Versions:
```
$ node-sass --version
node-sass	3.5.0-beta.1	(Wrapper)	[JavaScript]
libsass  	3.3.3	(Sass Compiler)	[C/C++]
```

SASS source:
```sass

#footer {
	nav {
		...
		@at-root #leftButton, #rightButton {
			...
			&:not(.none):active {
				background-color: green;
			}
		}
	}
}
```

Transpiled CSS:
```CSS
    #leftButton:not(.none, .none):active, #rightButton:not(.none, .none):active {
      background-color: green; }
```

Expected CSS:
```CSS
    #leftButton:not(.none):active, #rightButton:not(.none):active {
      background-color: green; }
```

**Comment by mgreter** [comment] 2016-04-05 09:16
Duplicate of https://github.com/sass/libsass/issues/1901 and already fixed in 3.3.4

**Closed by mgreter** 2016-04-05 09:16 UTC
