### ISSUE TITLE
List items dropped when called in function with variable-length args

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1604] opened 2015-10-17 03:07 UTC
**TEST:**
```scss
@function test($args...) {
  $all: ();

  @each $arg in $args {
    $all: append($all, $arg);
  }

  @return inspect($all);
}

test {
  args-1: test(1 2 3);
  args-2: test(1 2, 3 4);
  args-3: test(1, 2, 3); // control - this works in all versions
}
```

**EXPECTED:** (LibSass 3.2.5 and Ruby Sass 3.4.14)
```
test {
  args-1: (1 2 3);
  args-2: (1 2) (3 4);
  args-3: 1 2 3; 
}
```

**ACTUAL:** (LibSass 3.3.0-beta3)
```
test {
  args-1: 1;
  args-2: 1 3;
  args-3: 1 2 3;
}
```

**Comment by xzyfer** [comment] 2015-10-17 04:02
Thanks for the report @davidkpiano. This appears to be a duplicate of https://github.com/sass/libsass/issues/1602 but I'm going to make this authoritative because it's clearer.

**Comment by xzyfer** [comment] 2015-10-19 06:45
Specs added https://github.com/sass/sass-spec/pull/544

**Closed** 2015-10-19 06:56 UTC
Labels: Bug - Confirmed, Bug - Regression, Dev - Needs Test, Release - Blocker
