### ISSUE TITLE
Source map references incorrect

### ISSUE THREAD

**Issue by joelworsham** [sass/libsass#1052] opened 2015-04-06 15:09 UTC
The source map outputted seems to be referencing incorrect file lines, though the files are correct.

If I open the source map itself, the "mappings" property has a bunch of semi-colons at the beginning.
```
"mappings": ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ACQA;EACE,aAAa;;EACb,sBAAsB;;EACtB,0BAA0B;;;;;...
```
If I delete all but one, then everything works fine.

**Comment by joelworsham** [comment] 2015-04-06 15:21
Here's some info about my project:

Using Foundation CSS framework SCSS by Zurb. Using Normalize (important from SCSS), http://git.io/normalize.

Main.scss
```
// Vendor
@import "../vendor/css/normalize";

// Deps
@import "settings.scss";

// Foundation
// Here we control all of the various foundation components to use
@import "../vendor/sass/foundation/components/visibility";
@import "../vendor/sass/foundation/components/clearing";
@import "../vendor/sass/foundation/components/grid";
@import "../vendor/sass/foundation/components/buttons";
@import "../vendor/sass/foundation/components/type";
@import "../vendor/sass/foundation/components/forms";

// Setup
@import "base";

// Static
@import "static/header";
@import "static/footer";

// Templates
@import "templates/single-post";
@import "templates/page";
@import "templates/common";

// Overrides
@import "wp";
```

**Comment by dwightjack** [comment] 2015-04-07 14:04
Hi I'n not sure my issue is exaclty the same as @joelworsham . Anyway since I updated to latest beta version, source maps seems to be broken when using `@extend`  feature.

Scenario:

```scss
//SCSS
%test {
	font-size: 10px;
}

a {
	background-color: red;
}

p {
	@extend %test;
}
```

```css
//CSS
p {
  font-size: 10px; }

a {
  background-color: red; }


/*# sourceMappingURL=style.css.map */
```

```
//Generated sourcemap
{
	"version": 3,
	"file": "style.css",
	"sources": [
		"style.scss"
	],
	"sourcesContent": [],
	"mappings": "AAAO,AACN,AAAW,AAGZ,AACC,AAAkB",
	"names": []
}
```


When I inspect the `p` tag the Dev Tool refers to the `a` tag rule (line 6).

In my build workflow a similar scenario is causing autoprefixer sourcemaps to break with an error:  `No element indexed by -1`

**Comment by mgreter** [comment] 2015-04-07 17:31
IMO we have two issues reported here!

@joelworsham your output looks very old. I know we had that bug in previous version, where too many lines are counted (which is the reason why you get so many `;;;;;`). Please test with latest beta and open a new issue if the problem persists.

@dwightjack Thanks for your really usefull and complete bug report (I wished all of them looked like that). IMO the message `by -1` tells that it is probably a duplicate of https://github.com/sass/libsass/issues/1056!

**Closed by mgreter** 2015-04-07 17:31 UTC
Labels: bug, sourcemaps

**Comment by dwightjack** [comment] 2015-04-07 18:19
Thank you and all the team for the great effort you're putting in the project!
