### ISSUE TITLE
Windows Path Containing Backslashes Fails

### ISSUE THREAD

**Issue by destroyerofbuilds** [sass/libsass#2181] opened 2016-09-20 19:08 UTC
This is a follow-up to a previous issue I filed revolving around Windows paths: maoberlehner/node-sass-glob-importer/issues/9

A full discussion of the issue, and the failed results, are discussed there.

However, in summary, using a [custom importer](https://github.com/maoberlehner/node-sass-glob-importer) that generates absolute paths on Windows using Node's `path.resolve`, I get something like: `@import 'C:\Users\hbetts\Workspace\node-sass-windows\app\components\components.scss';`

We can reproduce the issue using the following project: https://gitlab.com/hutson/node-sass-windows

Take import statement I provided above and place it in a new file called `app/example.scss`.

Then change the contents of `app/components/components.scss` to remove the import glob statement.

Lastly run the following command over the project:

```bash
./node_modules/.bin/node-sass app/example.scss -o dist
```

I end up with the following error:

```json
{
  "status": 1,
  "file": "C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\npp\fomponents\fomponents.scss\nParent style sheet: C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss",
  "formatted": "Error: File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\n       pp\fomponents\fomponents.scss\n       Parent style sheet: C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss\n        on line 1 of app/example.scss\n>> @import 'C:\\Users\\hbetts\\Workspace\\node-sass-windows\\app\\components\\components\n   ^\n"
}
```

version info:
```bash
$ ./node_modules/.bin/node-sass --version
node-sass       3.10.0  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```

**Comment by nschonni** [comment] 2016-09-20 21:45
I think Windows sytyle paths have some workarounds in Ruby Sass, but you should use URL style paths along withe the `includePaths` since you're using node-sass.

**Comment by mgreter** [comment] 2016-09-21 08:31
The problem is the following line in the CSS:
```
@import 'C:\Users\hbetts\Workspace\node-sass-windows\app\components\components.scss';
```

The whole issue can be simplified to:

main.scss:
```scss
@import '.\inc.scss';
``` 

inc.scss
```scss
result { success: true; }
```

sassc:
```cmd
# sassc main.scss
Error: File to import not found or unreadable: .inc.scss
       Parent style sheet: d:/lbstst/main.scss
        on line 1 of main.scss
>> @import '.\inc.scss';
```

ruby sass:
```cmd
# sass main.scss
Error: File to import not found or unreadable: .inc.scss.
        on line 1 of main.scss
  Use --trace for backtrace.
```

Closing as we behave as ruby sass does. I don't think it makes sense to have special parsing grammar just for unwrapped import statement (since it would contradict basic css parsing rules for escape sequences). But feel free to open a Feature Request with ruby sass if you think this should be possible.

**Closed by mgreter** 2016-09-21 08:31 UTC
