### ISSUE TITLE
placeholder renders if defined twice

### ISSUE THREAD

**Issue by jamesarosen** [sass/libsass#2712] opened 2018-08-24 20:16 UTC
If a file containing CSS rules imports a file containing only placeholders that has already been imported, the rules are rendered by both the placeholder file and the CSS file. Note that I'm not importing a file containing any CSS twice.

## input.scss

```scss
// top.scss
@import './placeholder';
/* in-between */
@import './utility';
```

```scss
// _placeholder.scss
%green { color: green; }
```

```scss
// _utility.scss
@import './placeholder'; // omitting this eliminates the duplication in output
.green { @extend %green; }
```

## Actual results

```bash
$ node_modules/node-sass/bin/node-sass top.scss
```

```css
.green {
  color: green; }

/* in-between */
.green {
  color: green; }
```

## Expected result

```css
/* in-between */
.green {
  color: green; }
```

version info:
```cmd
$ node_modules/node-sass/bin/node-sass --version
node-sass	4.9.3	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```

**Comment by jamesarosen** [comment] 2018-08-24 20:17
Adding an unused placeholder has no effect on output:
```scss
// _placeholder.scss
%green { color: green; }
%purple { color: purple; }
```
```css
.green {
  color: green; }

.green {
  color: green; }
```

**Comment by jamesarosen** [comment] 2018-08-24 20:18
Defining the placeholder twice and doing no imports has the same effect:
```scss
// top.scss
%green { color: green; }
%green { color: green; }
.green { @extend %green; }
```
```css
.green {
  color: green; }

.green {
  color: green; }
```

**Comment by jamesarosen** [comment] 2018-08-24 20:20
Adding some comments shows that the CSS is being emitted by the placeholder both times and never by the actual CSS rule.

### Input
```scss
/* a */
%green { color: green; }
/* b */
%green { color: green; }
/* c */
.green { @extend %green; }
/* d */
```

#### Actual Output
```css
/* a */
.green {
  color: green; }

/* b */
.green {
  color: green; }

/* c */
/* d */
```

#### Expected Output
```css
/* a */
/* b */
/* c */
.green {
  color: green; }
/* d */
```

**Comment by nschonni** [comment] 2018-08-24 23:35
Didn't try with separate files yet, but I see the same results for the Reference Ruby version (although selector order is different).

**Comment by xzyfer** [comment] 2018-08-25 02:42
I think the behaviour is intended. Can you confirm by trying with dart-sass?

**Comment by jamesarosen** [comment] 2018-08-25 17:29
> Can you confirm by trying with dart-sass?

```bash
$ node_modules/.bin/sass --version
1.13.0 compiled with dart2js 2.0.0
```
```css
$ node_modules/.bin/sass top.scss
/* a */
.greener, .green {
  color: green;
}

/* b */
.greener, .green {
  color: green;
}

/* c */
.greener {
  font-weight: bold;
}

/* d */
```

> I think the behaviour is intended.

From the [sass-lang documentation](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholder_selectors_foo):

> On their own, without any use of @extend, rulesets that use placeholder selectors will not be rendered to CSS.

That's ambiguous and I can see how one interpretation might be

> placeholder selectors render in-place when rulesets reference them

But I think it would be equally valid to assume they act like mixins:

```scss
/* a */
@mixin green { color: green; }
/* b */
@mixin green { color: green; }
/* c */
.green { @include green; }
.greener { @include green; font-weight: bold; }
/* d */
```

```css
$ node_modules/.bin/sass top.scss
/* a */
/* b */
/* c */
.green {
  color: green;
}

.greener {
  color: green;
  font-weight: bold;
}

/* d */
```

**Comment by bskibinski** [comment] 2018-10-04 15:08
There is no bug here, this is the way extends are supposed to work.
In your very first example, the duplication occurs because you're doing a "double" import of "@import './placeholder'", let me show you:

in top.scss you import these two files:
@import './placeholder';
@import './utility';

And in utility.scss, you import placeholder.scss again.
So, top is importing placeholder and utility. And utility also imports placeholder.

So what you get in your compiled top.scss is the folowing code:
%green (imported through top.scss)
%green (imported throught utility.scss)
and then you get the .green class, which will extend into the 2 the two %green placeholders.

Be sure you import all your partials in one main document, so you don't get this.

**Below another example explaining that extends should work like this:**
You've defined two placeholder tags (with the same name %green).
So the .green class gets extended into the 2 separate %green placeholders.

Extends are not like mixins, so the properties aren't added to the class .green.
Instead, the class .green gets added to the place where %green placeholder is defined.

So in your example:
**Input**
`/* a */
%green { color: green; }
/* b */
%green { color: green; }
/* c */
.green { @extend %green; }
/* d */`

**Output**
`/* a */
.green {
  color: green; }

/* b */
.green {
  color: green; }

/* c */
/* d */`
The above is the correct behavior for extends.

**Expected output**
`/* a */
/* b */
/* c */
.green {
  color: green; }
/* d */`
The output above is wrong, this is kind of how mixins work.

**Comment by jamesarosen** [comment] 2018-10-04 15:13
Fair enough, I guess. This just means I’ll always use mixins instead of placeholders since I want to allow consumers to declare their dependencies as they see fit.

**Comment by bskibinski** [comment] 2018-10-04 15:23
Mixins and extends are 2 completely different beasts.
My advice would be to steer clear of extends if you don't see any clear benefits, it can be tricky to get your head around, and could easily create specificity 'bugs'.

And actually modern zipping of css has actually made mixins preferable over extends the way compressing files works, you get a smaller file size using mixins (even though the css file using mixins will be a lot bigger, but it gets compressed better).

**Comment by xzyfer** [comment] 2018-11-27 08:47
Closing this since the behaviour is by design.

**Closed** 2018-11-27 08:47 UTC
