### ISSUE TITLE
Nested media query logic sometimes broken in 3.2

### ISSUE THREAD

**Issue by callumacrae** [sass/libsass#1224] opened 2015-05-18 14:18 UTC
I believe this was caused by #800.

Updating to libsass 3.2 broke some stuff with nested media queries in my styling. Here is a gist with the SCSS, and the 3.1 and 3.2 output: https://gist.github.com/callumacrae/c38f95172c2a8c7aebe4

I have no idea what is going on, and I can't contribute a failing test case because I don't know C.

**Comment by xzyfer** [comment] 2015-05-27 07:28
Please a copy pastable sample that reproduces the issue you're describing. Use sassmeister.com. As it stands we cannot progress this issue because we cannot reproduce it with the code supplied.

**Comment by callumacrae** [comment] 2015-05-27 09:45
```sass
@media all and (max-width: 768px) {
  @media only screen and (min-device-pixel-ratio: 2), only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi) {
    body .div {
      color: blue;
    }
  }
}
```

Output:

```css
@media {
  body .div {
    color: blue;
  }
}
```

Expected output:

```css
@media only screen and (min-device-pixel-ratio: 2) and (max-width: 768px), only screen and (-webkit-min-device-pixel-ratio: 2) and (max-width: 768px), only screen and (min-resolution: 192dpi) and (max-width: 768px) {
  body .div {
    color: blue;
  }
}
```

**Comment by xzyfer** [comment] 2015-05-27 22:23
Please use http://sassmeister.com in the future. This code provided produces no output in Sass. Technically the bug here is that we produce any output at all.

**Comment by xzyfer** [comment] 2015-05-27 22:27
No output is produced because `all` and `screen only` are incompatible and cannot be merged in a semantically accurate way.

```scss
@media all and (max-width: 768px) {
  @media only screen {
    a { b: c; }
  }
}
```

**Comment by xzyfer** [comment] 2015-05-27 22:44
Spec added https://github.com/sass/sass-spec/pull/396

**Closed** 2015-05-28 02:14 UTC
Labels: bug, PR Ready, test written

**Comment by callumacrae** [comment] 2015-05-28 07:53
What?

Of course they can be merged. It works as nested media queries as raw CSS, but then doesn't work in IE8 because it doesn't support nested media queries.

"only screen" matches both "all" and "only screen".

Try it as CSS. It works. SASS breaks it.

**Comment by xzyfer** [comment] 2015-05-29 16:50
Libsass is an implementation of the Sass language. The Sass language to not
allow for combining these media queries. If you think it should please open
an issue with the official library http://github.com/sass/sass/issues.

As far as the language is concerned the bug here is that we supported this
behaviour, however broken it was.

**Comment by callumacrae** [comment] 2015-05-30 08:47
Fair enough. Thanks.

**Comment by nex3** [comment] 2018-12-08 01:35
I just came across this as part of fixing https://github.com/sass/dart-sass/issues/537. LibSass's behavior here is incorrect, and Dart Sass is going to start implementing this correctly once https://github.com/sass/dart-sass/pull/539 lands. I'm going to re-open this so I have an issue to link to in the options.yml file.
