### ISSUE TITLE
@use not implemented

### ISSUE THREAD

**Issue by stefanloerwald** [sass/libsass#3121] opened 2020-07-23 09:11 UTC
`@use` rules seem to be not implemented:

foo.scss:
```css
body {
    color: green;
}
```

bar.scss:
```css
@use "foo";
```

I would expect the result to be

bar.css:
```css
body {
    color: green;
}
```

However, I get

```css
@use "foo";
```

I use the [C# compiler frontend](https://github.com/Taritsyn/LibSassHost) which uses version 3.6.4 of libsass.

**Comment by connorskees** [comment] 2020-07-28 04:26
Hello,

This appears to be a duplicate of https://github.com/sass/libsass/issues/2807. The lack of `@use` support is a known issue of `libsass`.

**Comment by stefanloerwald** [comment] 2020-07-28 06:05
Thanks for your reply @connorskees. Is this something that is worked on?

**Comment by xzyfer** [comment] 2020-07-28 06:14
This is not currently being worked on. There's is ongoing work to refactor the core of LibSass to make this feature easier to implement.

**Closed by xzyfer** 2020-07-28 06:14 UTC

**Comment by drwpow** [comment] 2020-08-24 18:55
@xzyfer I’d love to help add this, if possible. Is there a smaller issue I can tackle that’d help move toward this?
