### ISSUE TITLE
Compiling error with color assigned variables

### ISSUE THREAD

**Issue by IrvingArmenta** [sass/libsass#2225] opened 2016-11-12 01:24 UTC
### Compiling error with color assigned variables using gulp-sass and node-sass to compile

main.sass
```scss
@import "partials/_variables"
@import "vendor/normalize"
@import "vendor/skeleton"
@import "partials/_header"
@import "partials/_main-home"
@import "partials/_footer"
@import "partials/_intro"
```

partials/_variables.sass 
```
// z-index levels
$on-bottom: 2
$on-middle: 3
$on-top: 4

// media breakpoints
$large-desktop: "(min-width: 1200px)"
$desktop: "(min-width: 992px)"
$tablet: "(min-width: 768px)"
$phone-only: "(max-width: 550px)"

// Colors
$primary: #1EAEDB
$black: #000000
$white: #ffffff
```

All of the other variables work fine, however if i use any "Colors" variable like this:

```
body
    background-color: $primary
```
It just makes the gulp-sass task end abruptly, with no error message, no nothing, just "sass ..." on the CMD, (sass is the name of the task in the gulpfile.js) Any idea why is this happening? 

This is the gulp task from the gulpfile.js:

```
gulp.task('sass', function () {
  return gulp.src('./public/sass/**/*.sass')
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(gulp.dest('./public/css'))
    .pipe(notify("Compilation success!"));
});
```

I could publish my project on a repository if needed to check thoroughly, I'm desperate because it just doesn't make sense, tried to open an issue on gulp-sass but i was just told it wasn't a gulp-sass issue and had my issue closed. 

Thought maybe it could be a ".sass" format related issue, but it happens the same with ".scss" files, so I don't think that is the problem.

```
node version: 6.8.0 
npm version: 3.10.9 
```

version info:
```cmd
$ node-sass --version
node-sass       3.10.1   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```

**Comment by xzyfer** [comment] 2016-12-05 09:36
@IrvingArmenta were able to resolve your issue? I suspect it's due to your missing `includePaths` config in gulp-sass.

**Comment by IrvingArmenta** [comment] 2016-12-05 20:50
@xzyfer still not working; The other variables work fine, and also, if i put the variable inside the same file, like on top of the same document, I get the same result, the task just ends with no error message. :/

**Comment by xzyfer** [comment] 2016-12-06 00:50
>if i put the variable inside the same file, like on top of the same document, I get the same result, the task just ends with no error message

Can you please provide an example I can compile myself to see this issue?

**Comment by IrvingArmenta** [comment] 2016-12-06 04:47
Is very simple, any file, even something like this:

example.sass 
```
$primary: #000000
$secondary: #959595

body
  background-color: $primary
  color: $secondary
```

something like this, It just ends the task, on the CMD, it only ends like "sass ..." and that's it, there is no error message or anything, but if i don't use that kind of variable, it compiles just fine, so i'm not sure what is the problem.  

I'm using .sass files not .scss, I tried using .scss but it's the same problem, I'm on Windows 7 ultimate 64x, not sure if that's an issue, I used to compile with an old version of node, and npm, and it worked fine before, I updated and this happened, I have updated and re-installed everything (everything) multiple times, so that is why i decided to put an issue here.

**Comment by mgreter** [comment] 2016-12-06 08:59
@IrvingArmenta [I cannot reproduce a problem with your code][1]!?
I also tested your code snippet locally in sass format without any problem!?

[1]: http://libsass.ocbnet.ch/srcmap/#JHByaW1hcnk6ICMwMDAwMDA7CiRzZWNvbmRhcnk6ICM5NTk1OTU7Cgpib2R5IHsKICBiYWNrZ3JvdW5kLWNvbG9yOiAkcHJpbWFyeTsKICBjb2xvcjogJHNlY29uZGFyeTsKfQ==

**Comment by xzyfer** [comment] 2016-12-06 10:19
@IrvingArmenta can you please provide the gulp-sass config you're using. I'm pretty sure this is a config issue on your end.

**Comment by IrvingArmenta** [comment] 2016-12-06 18:30
this is the content of my gulpfile.js 

```
'use strict';

let gulp = require('gulp');
let sass = require('gulp-sass');
let notify = require("gulp-notify");
let concat = require('gulp-concat');
let uglyfly = require('gulp-uglyfly');

gulp.task('sass', function () {
  return gulp.src('./public/sass/**/*.sass')
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(gulp.dest('./public/css'))
    .pipe(notify("Compilation success!"));
});

gulp.task('scripts', function() {
  return gulp.src('./public/js/*.js')
    .pipe(concat('web-app-min.js'))
    .pipe(uglyfly())
    .pipe(gulp.dest('./public/js/output'))
    .pipe(notify("Scripts done!"));
});

gulp.task('watch', function () {
  gulp.watch('./public/sass/**/*.sass', ['sass']);
  gulp.watch('./public/js/*.js', ['scripts']);
});

gulp.task('default', ['scripts', 'sass', 'watch']);
```
"scripts" task works fine.

Is this what you mean by my gulp-sass config? or where do i get that data from?  sorry, I know gulp in a very superficial way.

**Comment by xzyfer** [comment] 2016-12-06 23:36
Thanks could you also supply the output of `npm ls node-sass`

**Comment by IrvingArmenta** [comment] 2016-12-07 03:02
I got

```
'-- gulp-sass@2.3.2
  '-- node-sass@3.11.2
```

**Comment by IrvingArmenta** [comment] 2016-12-28 23:22
Hello, I got a different cmd and this is what throws me when I try to compile SASS with a color variable:

`/cygdrive/c/Users/ir/AppData/Roaming/npm/gulp: line 14:  6904 Illegal instruction     node "$basedir                                            /node_modules/gulp/bin/gulp.js" "$@"
`
I hope this can help to fix my issue : /

**Comment by xzyfer** [comment] 2016-12-29 05:02
Sounds like you have broken Sass. Please try using gulp-ruby-sass and fix any errors it reports.

**Comment by mgreter** [comment] 2017-01-18 00:16
Closing as we need a more specific test case to reproduce!
Please re-open if you can provide such a case! Thanks!

**Closed by mgreter** 2017-01-18 00:16 UTC
