### ISSUE TITLE
Linebreaks are removed when a file is imported inside a media query

### ISSUE THREAD

**Issue by andfinally** [sass/libsass#1103] opened 2015-04-14 11:37 UTC
We have a bunch of SCSS files which we import into a global.scss file. Some of them are imported inside media queries, for example:

```sass
@import "header";
@import "footer";
@import "forms";
@import "posts";

@media screen and (min-width: 480px) {
    @import "media-query-480";
}

@media screen and (min-width: 768px) {
    @import "media-query-768";
}
```

This gives us several separate CSS files and a concatenated one for prod. When I run gulp-sass, the line breaks between rules are preserved in the individual files, so in media-query-480.scss:

```sass
.entry-meta-date {
  display: block;
}

.entry-meta-date .day {
  display: inline;
}

.entry-meta-date-under {
  display: none;
}
```

becomes 

```css
.entry-meta-date {
  display: block; }

.entry-meta-date .day {
  display: inline; }

.entry-meta-date-under {
  display: none; }
```

but in the corresponding part of global.css it's

```css
 .entry-meta-date {
    display: block; }
  .entry-meta-date .day {
    display: inline; }
  .entry-meta-date-under {
    display: none; }
```

which is hard to read in a big CSS file. Not sure if this is a bug, but it's not the behaviour I'd expect.

**Comment by andfinally** [comment] 2015-04-14 12:53
I've since found this seems to apply to all code inside media queries - when I remove the media queries from global.scss and wrap them around the code in media-query-480.scss, that CSS turns out munged together too.

**Comment by xzyfer** [comment] 2015-04-14 13:16
Thanks for the report @andfinally. We're scheduling whitespace related issue for the 3.4 release since they're non-critical.

Related https://github.com/sass/libsass/issues/1030

**Comment by andfinally** [comment] 2015-04-14 14:27
Thanks @xzyfer!

**Comment by xzyfer** [comment] 2015-04-25 04:02
Specs added https://github.com/sass/sass-spec/pull/348

**Comment by hcatlin** [comment] 2015-04-29 23:08
Actually, I'm pretty sure this got resolved with 3.2

**Comment by mgreter** [comment] 2015-11-07 02:06
Looks like duplicate of https://github.com/sass/libsass/issues/1030

**Comment by xzyfer** [comment] 2015-11-08 07:06
Technically yes but it's a specific case we can test against.

**Comment by mgreter** [comment] 2016-01-09 16:46
Closing this in favor of https://github.com/sass/libsass/issues/1030 sinceupstream confirmed a bug how double line endings are handled. The behavior here is seen because we tried to emulate the buggy ruby sass behvaior. So lets wait and see what upstream sass will do.

**Closed by mgreter** 2016-01-09 16:46 UTC
Labels: Bug - Confirmed, Bug - Whitespace, Dev - Test Written
