### ISSUE TITLE
Invalid CSS generated with 2.3.0 (Nesting + child combinator + selector lists + interpolation)

### ISSUE THREAD

**Issue by ahorek** [sass/libsass#3083] opened 2020-04-30 14:55 UTC
links with https://github.com/sass/sassc-ruby/issues/198

**Comment by ahorek** [comment] 2020-04-30 15:28
I can confirm that this issue has been fixed in master https://github.com/sass/sass-spec/pull/1528 and the expected output is the same as what dart-sass generates.

but it's broken in the latest libsass release 3.6.3 (regressed between 3.6.1 - 3.6.3)

this is a serious problem because it silently generates broken stylesheets without any warning. Unfortunately, our CI didn't catch this earlier.

any chance for a bugfix release from the current master?

cc @mgreter @glebm

**Comment by mgreter** [comment] 2020-04-30 20:11
Thanks for the spec! This is a duplicate of https://github.com/sass/libsass/issues/3046 and https://github.com/sass/libsass/issues/3053. It probably merits to do a release soon to address this.

**Closed** 2020-05-01 01:27 UTC
Labels: Dev - Test Written, Invalid - Duplicate
