### ISSUE TITLE
Parse error when a url is protocoll-less

### ISSUE THREAD

**Issue by hhofstaetter** [sass/libsass#2123] opened 2016-07-15 16:05 UTC
Parsing of the input does not work if there is no space between `:` and `url(` when the url is protocol (`//foo.com`) and not enclosed in quotes. 

``` css
foo {
  bar:url(//foo.bar/favicon.ico);}
```

Ruby Sass

``` css
foo {
  bar: url(//foo.bar/favicon.ico); }
```

LibSass

```
Error: Invalid CSS after "...r/favicon.ico)}": expected ")", was ""
        on line 3 of test.scss
>>   bar:url(//foo.bar/favicon.ico)}
```

Spec added https://github.com/sass/sass-spec/pull/879
##

**Comment by xzyfer** [comment] 2016-07-19 04:36
@hhofstaetter thanks for the report. I've been able to reproduce this with 3.3.6. I'll need to confirm it's still an issue in the upcoming 3.3.7.

**Comment by xzyfer** [comment] 2016-09-22 11:53
Had a look into this. It's related to the selector lookahead. We don't currently have a equivalent of Sass' `try_declaration`. Moving this off the 3.4 critical path since it's an edge case.

**Comment by mgreter** [comment] 2017-05-20 22:58
Fixed by https://github.com/sass/libsass/pull/2387

**Closed by mgreter** 2017-05-20 22:58 UTC
Labels: Bug - Confirmed, Dev - Test Written, Sass 3.4 Compatibility
