### ISSUE TITLE
after upgrading compile issue with transition: transform short hand

### ISSUE THREAD

**Issue by lukerobertson1** [sass/libsass#1697] opened 2015-11-04 11:13 UTC
Hello,

so i upgraded grunt sass on my project and noticed after it had broken a lot of sections of the site, after a panic i found the follow change in post complied code caused the issue:

precompiled (with http://bourbon.io/):

    @include transition(transform 1s ease-in-out, height .5s ease-in-out);
 

before upgrade post-compiled:

    -webkit-transition: -webkit-transform 1s ease-in-out, height .5s ease-in-out;
    -moz-transition: -moz-transform 1s ease-in-out, height .5s ease-in-out;
    transition: transform 1s ease-in-out, height .5s ease-in-out;

after upgrade post-compiled:

    webkit-transition: -webkit-transform, height;
    -moz-transition: -moz-transform, height;
    transition: transform, height;
 

the transition mixin works fine for everything else other than the transforms

is this a legit bug or something my side?

**Comment by xzyfer** [comment] 2015-11-04 12:06
This is a duplicate of https://github.com/sass/libsass/issues/1645. Please subscribe to that issue for updates.

**Closed by xzyfer** 2015-11-04 12:06 UTC
