### ISSUE TITLE
Copyleft (CC-BY-SA) code in sass2scss.cpp

### ISSUE THREAD

**Issue by hyandell** [sass/libsass#3146] opened 2021-02-19 01:07 UTC
Just noting that you have copyleft code in the https://github.com/sass/node-sass/blob/master/src/libsass/src/sass2scss.cpp file - the piece of code copied from StackOverflow. This seems out of sync with your overall MIT licensing.

**Comment by nschonni** [comment] 2021-02-19 03:05
Duplicate of #3009

**Closed by nschonni** 2021-02-19 03:05 UTC

**Comment by mgreter** [comment] 2021-02-28 05:35
With upcoming LibSass 4.0 this will be no longer an issue for LibSass, as the whole sass parsing will be replaced.
None the less, the sass2scss repo will probably stay up. So I will add a few comments:

It is correct that stack-overflow code is generally considered incompatible with MIT license, but there is also the note of code being to trivial to license. And yes, the mentioned code does exactly what it is supposed to do. If I would rewrite the code, it would pretty much end up in the exact same way as the referenced snippet. And I'd rather let the reference there so people can understand why that code does what it does. Which is probably why OP found it in the first place due to the proper attribution.

Don't get me wrong, licenses are important and IP is something to be protected. I know that oracle and goggle argued over a nine line function for IP. So would it be better if I condensed the code down to 6 lines?

```
std::istream::sentry se(is, true);
std::streambuf* sb = is.rdbuf();
if (sb->sbumpc() == '\n') { return is; }
else if (sb->sbumpc() == '\r') { return sb->sgetc() == '\n' ? sb->sbumpc() : is; }
else if (sb->sbumpc() == EOF) { t.empty() ? is.setstate(std::ios::eofbit) : is; }
else { t += (char)c; }
```

There is nothing I can get rid of, because it will then not behave as it should. I can of course implement the same thing less efficient, but I kinda refuse to do so since I know how it must be implemented. I hope this satisfies the inquiry by @hyandell and if not I sure hope my legal expenses insurance will cover that 🙏
