### ISSUE TITLE
Selectors out of order when using @extend without white space divider

### ISSUE THREAD

**Issue by andybenedict** [sass/libsass#1539] opened 2015-09-06 13:36 UTC
When extending a selector (or silent selector) the output gets out of order when there is no white space after the selector.

For example:
```
.foo{
  &.disabled{
    display: none;
  }
}

.bar {
  @extend .foo;
}
```
outputs as:
```
.foo.disabled, .disabled.bar {
  display: none;
}
```
instead of:
```
.foo.disabled, .bar.disabled {
  display: none;
}
```

While this is not a major issue with selectors which can be in any order, it produces invalid CSS when dealing with an attribute where:
```
.foo{
  &[disabled]{
    display: none;
  }
}

.bar {
  @extend .foo;
}
```
outputs as:
```
.foo[disabled], [disabled].bar {
  display: none;
}
```

I stumbled on this in some framework development I'm working on. Unfortunately, I am not familiar enough with C++ to take a crack at this one.

**Comment by xzyfer** [comment] 2015-09-06 13:46
This is a duplicate of https://github.com/sass/libsass/issues/1392, however we're not aware of the breaking with regards to attribute selectors. Thanks for the report @andybenedict

**Comment by andybenedict** [comment] 2015-09-06 14:07
Thanks for the quick response. You guys rock.

**Comment by mgreter** [comment] 2015-09-06 17:24
I get the same results for the following sample in ruby sass and latest master!?

```
.foo{
  &[disabled]{
    display: none;
  }
}

.bar {
  @extend .foo;
}
```

[1]:

**Comment by mgreter** [comment] 2015-09-06 19:34
@xzyfer can you please re-check? IMHO this is invalid or upstream bug, as ruby sass never produces:

```css
.foo.disabled, .bar.disabled {
  display: none;
}
```

**Comment by mgreter** [comment] 2015-09-06 19:44
Had to do some research concerning theclaim that the following is invalid CSS

```css
.foo[disabled], [disabled].bar {
  display: none;
}
```

> A simple selector is either a type selector or universal selector followed immediately by zero or more attribute selectors, ID selectors, or pseudo-classes, in any order. [1]

If one looks further down, we can see `5.8 Attribute selectors` and `5.8.3 Class selectors`, indicating they are considered equal. So with these two statements it's pretty clear that the above is valid css.

[1]: http://www.w3.org/TR/CSS21/selector.html#selector-syntax
[2]: http://www.w3.org/TR/CSS21/selector.html#attribute-selectors

**Comment by andybenedict** [comment] 2015-09-06 20:10
Sorry, I thought attribute selectors went wonky if they were ahead of the value. Must have set up my check in the browser wrong. 

I also pulled the sass  ruby gem (which I don't use because libsass is so much faster) and got the same sequencing problem. So it looks like it is upstream.

I'll move forward with my project and report this as a minor bug to the sass project.

Thanks again and sorry for the error and confusion. And you guys still rock!

**Comment by mgreter** [comment] 2015-09-06 20:12
Closing this as resolved! Thanks!

**Closed by mgreter** 2015-09-06 20:12 UTC
Labels: Bug - Maybe
