### ISSUE TITLE
@functions @for loop error #31

### ISSUE THREAD

**Issue by karneaud** [sass/libsass#1581] opened 2015-10-02 21:19 UTC
I refer to issue at https://github.com/stevenschobert/metalsmith-sass/issues/31

I was told to report the issue here. Can anyone offer any advice on this?

**Comment by saper** [comment] 2015-10-04 18:35
I can't reproduce the problem, can you post an example how are you invoking this function?

**Comment by karneaud** [comment] 2015-10-04 18:47
I'm using the latest version of metalsmith and metalsmith-sass to watch and compile my sass files to css via npm CLI

my metalsmith.json is 

```
  {
  "source": "app",
  "frontmatter":true,
  "destination": "/Users/kendallarneaud/Documents/SERVER/htdocs/fridgemusic",
  "metadata": {
    "site": {
      "title": "Jason 'Fridge' Seecharran - Fridge Music",
      "url": "http://www.fridgemusic.com",
      "author": "Kendall Arneaud",
      "keywords":"music,trinidad,r&b,rnb,caribbean,soul,calypso,reggae,artiste,vocalist",
      "description":"website of Trinidad based RnB artiste Fridge"
    },
    "stylesheets":
    {
      "main":"css/main.css"
    },
    "javascripts":
    {
      "modernizr":"js/vendor/modernizr.js",
      "jquery":"js/vendor/jquery.js",
      "others":["//cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.3/js/lightslider.min.js","//cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js","//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/ScrollToPlugin.min.js","//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js","//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/animation.gsap.js","//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js","//connect.soundcloud.com/sdk-2.0.0.js","//apis.google.com/js/client.js?onload=getYoutubeVideos","js/main.js"]
    }
  },
  "plugins": {
    "metalsmith-concat-convention": {
      "extname": ".concat"
    },
    "metalsmith-ignore":[".git",".gitignore",".gitmodules","README.md","*.json","{templates,partials,layouts,components,sass,js}/**","js/**/.*","!*.html","components/**/.*","!sass/*.scss"],
    "metalsmith-partial": {
      "directory": "app/partials",
      "engine":"handlebars",
      "preload":true
    },
    "metalsmith-layouts": {
      "engine": "handlebars",
      "default": "template.html",
      "directory": "app/templates",
      "partials":"app/partials",
      "pattern":"*.html"
    },
    "metalsmith-in-place":
    {
      "engine":"handlebars",
      "partials":"app/partials",
      "pattern": "*.html"
    },
    "metalsmith-sass":
    {
        "files":["app/sass/*.scss"],
        "includePaths":["app/sass"],
        "outputDir":"css",
        "outputStyle": "expanded",
        "indentedSyntax": true
    },
    "metalsmith-autoprefixer":
    {
      "files":{
        "/Users/kendallarneaud/Documents/SERVER/htdocs/fridgemusic/css/main.css":"main.css"
      },
      "browsers":"last 8 versions"
    },
    "metalsmith-browser-sync":
    {
      "proxy":
      {
        "target":"http://localhost:8080/fridgemusic"
      },
      "port":8080,
      "logLevel":"debug",
      "files":["app/sass/**/*","app/js/**/*","app/*.html","app/partials/**/*"],
      "server":false,
      "ignoreInitial":true,
      "reloadOnStart":true,
      "watchOptions":{ "ignoreInitial":true}
    }
  }
}
```

the particular sass code is as shown here https://github.com/stevenschobert/metalsmith-sass/issues/31 

along with the error

**Comment by saper** [comment] 2015-10-04 18:51
Can you install node-sass and just try to produce a small case to reproduce this? Just a single .scss file with your function and its invocation.

**Comment by karneaud** [comment] 2015-10-04 19:21
ok i installed a local node-sass into the project folder and ran

```
node_modules/.bin/node-sass test.scss test.css
```
on

```
@function makelongshadow($color, $len) {
  $val: 0px 0px $color;
  @for $i from 1 through $len {
    $val: #{$val}, #{$i}px #{$i}px #{$color};
  }
  @return $val;
}

@mixin longshadow($color, $len:34) {
  text-shadow: makelongshadow($color, $len);
}

.test
{
  @include longshadow(black);
}

```

and got 

> {
  "message": "error parsing interpolated value",
  "column": 11,
  "line": 4,
  "file": "/Users/kendallarneaud/Documents/Git/fridgemusic/test.scss",
  "status": 1
}

**Comment by saper** [comment] 2015-10-04 19:36
Thanks. I can confirm this is an issue with libsass 3.2.5 (current release bundled with node-sass 3.3.3) but it got fixed in libsass 3.3.0-beta2, which you can try by installing `npm install node-sass@beta`.

**Comment by karneaud** [comment] 2015-10-04 19:38
@stevenbedrick  FYI

**Comment by karneaud** [comment] 2015-10-09 21:09
updated to node-sass@beta1 and got the error

> Mixin "clearfix" does not accept a content block

the clarify mixin

```
@mixin clearfix {
  *zoom: 1;

  &:before, &:after {
    content: " ";
    display: table;
  }

  &:after {
    clear: both;
  }
}
```

**Comment by davidkpiano** [comment] 2015-10-09 21:20
@karneaud That's expected. The `@mixin clearfix` needs to have `@content` inside the body to accept a content block.

**Closed** 2015-10-09 21:21 UTC
Labels: Bug - Confirmed
