### ISSUE TITLE
Error in @for loop in @function after manual incrementation 

### ISSUE THREAD

**Issue by NicolasGraph** [sass/libsass#2356] opened 2017-04-04 22:18 UTC
input.scss
```scss
@function foo() {
  $value: false;

  @for $i from 1 through 5 {
    @if $i < 5 {
      $i: $i + 1;
      $value: 'broken';
    }
  }
  
  @return $value;
}

.foo {
  width: foo();
}
```

libsass 3.5.0.beta.2 returns nothing or the following error:
```css
Undefined operation: "broken lt 5". on line 5 at column 9
```

ruby sass 3.4.21 or 4.0.0.alpha.1 work as expected:
```css
.foo {
  width: "broken";
}
```

If I do the same without the use of a function, it works with libsass.

input.scss
```scss
$value: false;

@for $i from 1 through 5 {
  @if $i < 5 {
    $i: $i + 1;
    $value: 'broken';
  }
}

.foo {
  width: $value;
}
```

libsass 3.5.0.beta.2:
```css
.foo {
  width: "broken";
}
```

version info:
```cmd
$ node-sass --version
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

**Comment by mgreter** [comment] 2017-04-05 00:53
I can't reproduce this with either libsass 3.4.4 or [3.5.0-beta-3][1]

[1]: http://libsass.ocbnet.ch/srcmap/#QGZ1bmN0aW9uIGZvbygpIHsKICAkdmFsdWU6IGZhbHNlOwoKICBAZm9yICRpIGZyb20gMSB0aHJvdWdoIDUgewogICAgQGlmICRpIDwgNSB7CiAgICAgICRpOiAkaSArIDE7CiAgICAgICR2YWx1ZTogJ2Jyb2tlbic7CiAgICB9CiAgfQogIAogIEByZXR1cm4gJHZhbHVlOwp9CgouZm9vIHsKICB3aWR0aDogZm9vKCk7Cn0=

**Comment by NicolasGraph** [comment] 2017-04-05 01:42
You can reproduce this in Sassmeister.

**Comment by mgreter** [comment] 2017-04-08 20:20
Closing as not reproducable. Might be a duplicate of https://github.com/sass/libsass/issues/2330

**Closed by mgreter** 2017-04-08 20:20 UTC
