### ISSUE TITLE
Invalid :not selector generated with @extend

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2139] opened 2016-08-04 10:50 UTC
Originally reported by @dreyks in https://github.com/sass/sassc/issues/180. Possibly a duplicate of #2055.

``` scss
 .base-class {
   color: #FFF;
 }

 .parent-class {
   .child-class {
     @extend .base-class;
     border: '1px';
   }
 }

 *:not(.base-class) {
   display: none;
 }
```

LibSass 3.3.6 (c6685d7)

``` css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class):not(.parent-class .child-class) {
  display: none; }
```

Sass 3.4.21

``` css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class) {
  display: none; }
```

``` cmd
sassc: 3.3.3-3-ge054
libsass: 3.3.6-90-gc6685
sass2scss: 1.0.6
```

Spec added https://github.com/sass/sass-spec/pull/888

**Comment by s-yadav** [comment] 2016-08-23 11:07
Got into same issue while upgrading from sass-rails to [sassc-rails](https://github.com/sass/sassc-rails)

**Comment by darklow** [comment] 2016-10-08 12:38
As a workaround I found that using attribute selector still works. Not perfect, but better than nothing.
```css
/* Instead of */
:not(.thing) {
    @extend .thing;
    background: blue;
}

/* You can write: */
&:not([class*="thing"]) {
    @extend .thing;
    background: blue;
}

**Comment by cmaart** [comment] 2017-01-17 09:38
Can confirm for:

```cmd
$ node-sass --version
node-sass       4.3.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
```

**Comment by xzyfer** [comment] 2017-01-17 23:05
Another example in https://github.com/dlmanning/gulp-sass/issues/583

**Comment by mgreter** [comment] 2017-01-17 23:54
Closing as duplicate of https://github.com/sass/libsass/issues/2055. I'm aware that extending wrapped selectors, `:not` is only one example, was never handled correctly by LibSass so far!

**Closed by mgreter** 2017-01-17 23:54 UTC
Labels: Bug - @extends, Bug - Confirmed, Dev - Test Written, Sass 3.4 Compatibility
