### ISSUE TITLE
CSS Custom Properties syntax is not supported as key for a map

### ISSUE THREAD

**Issue by jounik** [sass/libsass#1088] opened 2015-04-10 10:30 UTC
The following works with Ruby Sass 3.4.12

```sass
$map: (
  --custom-prop: "value"
);
```

LibSass 3.1.0 throws the following exception:

    _Map_base::at on line undefined at column undefined

Wrapping the key in quotes makes it work with LibSass as well:

```sass
$map: (
  "--custom-prop": "value"
);
```

Tested in sassmeister.com

**Comment by mgreter** [comment] 2015-04-10 10:44
This is a duplicate of https://github.com/sass/libsass/issues/1086

**Closed by mgreter** 2015-04-10 10:44 UTC

**Comment by jounik** [comment] 2015-04-10 10:58
Thanks! I tried to search for a similar issue, but obviously not hard enough :)
