### ISSUE TITLE
Sassc 3.1 compiled with LibSass 3.0.3?

### ISSUE THREAD

**Issue by camflan** [sass/libsass#892] opened 2015-02-18 21:55 UTC
I have used homebrew to install libsass and sassc before, but when updating to 3.1 (homebrew successfully installed both libsass 3.1 and sassc 3.1 to Cellar), sassc -v is reporting LibSass 3.0.3

```
$ sassc -v
sassc: 3.1.0
libsass: 3.0.3
sass2scss: 1.0.3
```

Because of this, I'm missing out on the awesome update to Libsass

**Comment by xzyfer** [comment] 2015-02-21 06:18
Hi @camflan pardon my naivety around brew. I think sassc binds to whichever version of Libsass you have installed. I could be that your brew was out of date when pulling Libsass.

Please uninstall both Libsass and sassc, update your brew, and reinstall. After updating brew you should get these versions from `brew info`.

```
➜  sassc git:(fbdc12b) ✗ brew info libsass
libsass: stable 3.1.0 (bottled), HEAD
https://github.com/sass/libsass
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsass.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✘
➜  sassc git:(fbdc12b) ✗ brew info sassc
sassc: stable 3.1.0 (bottled), HEAD
https://github.com/sass/sassc
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sassc.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✘, pkg-config ✔
Required: libsass ✘
```

***

If you problem persists please let us know.

**Comment by camflan** [comment] 2015-02-22 15:46
No problem. I deleted all traces of both sassc and libsass, upgraded homebrew and reinstalled. Still getting it bound to 3.0.3

I'll keep fiddling with it, unless you have another idea. thanks!

![screenshot 2015-02-22 09 44 30](https://cloud.githubusercontent.com/assets/27292/6319142/7f03b87a-ba77-11e4-82b0-aeb3bf4376a2.png)

**Comment by mgreter** [comment] 2015-02-22 17:59
Maybe it is linking against an old libsass system library?

**Comment by camflan** [comment] 2015-02-22 18:02
That's what I've been looking for. I've checked all of the /usr/ dirs, everything is symlinked to /usr/local/Cellar/libsass/3.1.0

Any other places it could be?

**Comment by mgreter** [comment] 2015-02-22 19:27
What does `ldd sassc` show?

**Comment by camflan** [comment] 2015-02-22 22:10
no ldd on mac, but here's what I got from otool

![screenshot 2015-02-22 16 09 29](https://cloud.githubusercontent.com/assets/27292/6320788/4003300c-baad-11e4-9529-0858b7e6c26f.png)

**Comment by dhruvbhatia** [comment] 2015-02-23 10:10
Experiencing the same issue:

![screen shot 2015-02-23 at 9 08 46 pm](https://cloud.githubusercontent.com/assets/1193022/6325916/502ed992-bba0-11e4-8e8c-084dc3985679.png)

**Comment by drewwells** [comment] 2015-02-23 14:07
I'm seeing the same problem:

```
-> % sassc --version
sassc: 3.1.0
libsass: 3.0.3
sass2scss: 1.0.3
-> % brew upgrade libsass
Error: libsass 3.1.0 already installed
-> % brew link libsass
Warning: Already linked: /usr/local/Cellar/libsass/3.1.0
To relink: brew unlink libsass && brew link libsass
```

It's possible the brew bottle has the wrong version baked into it, but it is in fact libsass 3.1.0.

**Comment by drewwells** [comment] 2015-02-23 14:23
Okay, the libsass brew bottle has the incorrect version in it. Not sure how this happened. It's building with the correct version of libsass, but libsass.pc has 3.0.3 in it.

```
prefix=@@HOMEBREW_CELLAR@@/libsass/3.1.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libsass
URL: https://github.com/sass/libsass
Description: A C implementation of a Sass compiler
Version: 3.0.3
Libs: -L${libdir} -lsass
Cflags: -I${includedir}
```

Checking out tree/3.1.0, I see that the 3.1.0 release does print the version 3.0.3 in `support/libsass.pc`.

```
autoreconf -fvi && ./configure --disable-shared --prefix=$(pwd) --disable-silent-rules --disable-dependency-tracking
-> % cat support/libsass.pc
prefix=/Users/drew/code/libsass
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libsass
URL: https://github.com/sass/libsass
Description: A C implementation of a Sass compiler
Version: 3.0.3
Libs: -L${libdir} -lsass
Cflags: -I${includedir}
```

So long story short, it's printing the wrong version but the correct version of libsass is in use. Given that homebrew doesn't support versioning, I don't recommend we bother fixing this.

**Comment by mgreter** [comment] 2015-02-23 17:39
I already suspected such a thing. I'm closing this as an upstream bug. Homebrew should do its homework and update that version when the package version is bumped. Preferably in an automated fashion. I guess the source tree has to be updated too, which implies that this version must be updated accordingly. I do it the same way when releasing `perl-libsass` (getting the version via git and writing it to a file; to be used later when the bindings get compiled).

@drewwells I actually had a look at some homebrew sassc/libsass repos today (googled it), but wasn't able to dig up anything suspicious. Maybe you could provide a link to `support/libsass.pc`?

**Closed by mgreter** 2015-02-23 17:39 UTC
Labels: clarify

**Comment by drewwells** [comment] 2015-02-23 17:45
We currently have to manually tag the releases of libsass. This is why the version being reported by homebrew is correct, but sassc thinks it is invalid. The autotools were still tagged as 3.0.3!

 I checked out the 3.1.0 release and it reported itself as 3.0.3 that's what my above comment is about. I'm not sure how autotools in C work, but it appears to be creating libsass.pc from this: https://github.com/sass/libsass/blob/3.1.0/configure.ac#L5

**Comment by mgreter** [comment] 2015-02-23 17:57
OK, there seems to be a problem in the autotools build (looks like homework for libsass too), but I'm not convinced that this is actually the cause for the original report. I'm pretty sure the actual shown version is defined [here] [1], as it really just shows the `LIBSASS_VERSION` makro, defined on compile time!
https://github.com/sass/libsass/wiki/Building-Libsass#including-the-libsass-version

[1]: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsass.rb#L21

**Comment by mgreter** [comment] 2015-02-23 17:58
Got it now, looks like in

**Comment by drewwells** [comment] 2015-02-23 18:14
homebrew doesn't define this version at all. Is there a fallback when the environment variable isn't defined?

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsass.rb#L21

    ENV["LIBSASS_VERSION"] = "HEAD" if build.head?

So on `brew install --head libsass` HEAD is reported as the libsass version, otherwise nothing is reported. When I did my run above, I didn't have `LIBSASS_VERSION` defined, and 3.0.3 was reported as the version in use.

**Comment by mgreter** [comment] 2015-02-23 18:21
We basically do not want to have any version numbers checked in into the libsass branch, since git itself should provide the version information. All official build "solutions" (beside MSVC I guess) can fetch the version from git directly or fallback to the env variable or finally fallback to a hardcoded string (`[na]` in the code). Now the autotools seems to fallback to the version of the package, which has the be static (and is 3.0.3 currently). But I will try to replace that too with an automated part (`m4_esyscmd` seems to be the friendly helper here). So in the long run, if you do not have the git repo around, you will need to provide the version from outside. I could be willing to add an additional fallback to get the version from a file (which should make it a little bit easier to automate this from third party sides).

But yeah, the way it was compiled, it actually should have reported `[na]` in the original report!

**Comment by drewwells** [comment] 2015-02-23 18:43
Hmm that is weird, I wonder why 3.0.3 is getting picked up.

A VERSION file would be ideal for homebrew that's how homebrew maintainers prefer to keep up with the current version. Personally, I don't have much of an opinion on how this should be done. I have been happy baking the version into wellington https://github.com/wellington/wellington/blob/master/.libsass_version. It works much better than many other alternative way of tracking upstream versions.

**Comment by mgreter** [comment] 2015-02-23 18:54
I could probably create a fallback to a VERSION file (for autotools). But I honestly do not want to have such a file checked in into the libsass repo itself. As I wrote earlier, I do it that way when I create a release of the perl bindings. I will probably change the autotools build to fall back to `[na]` when no version is passed, but I need to check first if autotools will behave correctly (otherwise I will probably just set it to 0.0.0).
