### ISSUE TITLE
Dynamic division with interpolation not compatible with libsass

### ISSUE THREAD

**Issue by atomicpages** [sass/libsass#948] opened 2015-03-15 17:04 UTC
Found this problem with playing with node-sass the other day with this code snippet:

```
@function _calcRU($px, $base, $unit) {
	$unit: quote($unit);

	@if not $unit == "em" or not $unit == "rem" or not $unit == "%" {
		@debug "Invalid unit, choose 'em' or 'rem'";
		@return null;
	}

	@if not unitless($px) {
		$px: strip-units($px);
	}

	@if not unitless($base) {
		$base: strip-units($base);
	}

	@if($unit == "%") {
		@return percentage($px / $base);
	}

	@return ($px / $base) * 1#{$unit};
}
```

This test with Sass 3.2.19  and above
```
body {
	font-size: _calcRU(12, 10, "%");
	font-size: _calcRU(16, 10, "rem");
	font-size: _calcRU(20, 10, "em");
	font-size: _calcRU(24, 10, "rem");
}
```

yields
```
body {
	font-size: 120%;
	font-size: 1.6rem;
	font-size: 2em;
	font-size: 2.4rem;
}
```

Testing with the current libsass master I get `"invalid operands for multiplication"`.

**Comment by mgreter** [comment] 2015-03-15 23:14
I can confirm that this bug exists on latest master.
Test case can probably be shortened to:
```CSS
foo { bar: 10 * 5#{px}; }
```

**Comment by mgreter** [comment] 2015-03-16 19:34
@xzyfer I gave it a try, but it is a bit more complicated than expected. Actually with my first approach it started to accept stuff like this (which I found quite neat, but is not what ruby sass does):

```CSS
10f#{o}o + 20foo -> 30foo
```

It also correctly complained when units where off for calculations. Not sure what the reasons are for ruby sass to not evaluate interpolated stuff into numbers again (there was actuall only one failing spec test with function `type` returning `number` instead of `string`). IMO ruby aborts the `Binary_Expression` parsing when it sees some interpolated stuff, which seems not that easy to implement currently (I suspect this has also something to do with our "everything is a space list" issue).

**Comment by xzyfer** [comment] 2015-03-17 01:50
I'm not surprised this is difficult. My initial impression was that this is related to https://github.com/sass/libsass/issues/442.

**Comment by HugoGiraudel** [comment] 2015-04-22 17:20
> Not sure what the reasons are for ruby sass to not evaluate interpolated stuff into numbers again (there was actuall only one failing spec test with function type returning number instead of string).

Because I believe Sass designers do not want units to be thought as a random string living at the end of a number. While there seem to be an issue with LibSass on this case, the initial problem could be solved by correctly using numbers with units, rather than dealing with strings all along.

**Comment by xzyfer** [comment] 2015-05-13 15:06
This fix was a false positive due to https://github.com/sass/sass-spec/pull/380. The spec still fails.

**Comment by mgreter** [comment] 2015-07-13 23:50
We now have a passing spec test since #1249 was merged :balloon:

**Closed by mgreter** 2015-07-13 23:50 UTC
Labels: Bug - Confirmed, Dev - PR Ready, test written
