### ISSUE TITLE
Implement @at-root selectors [$15]

### ISSUE THREAD

**Issue by Ne-Ne** [sass/libsass#353] opened 2014-05-06 13:41 UTC
I have noticed that when using:

    @at-root

With this code:

	@at-root{
		.list-date{
			float: left;
			display: block;
			width: 90px;
			height: 80px;
			margin-right:25px;
			color:white;
			background:url(/images/list-date-bg.svg) center no-repeat;

				.no-svg &{
					background-images:url(/images/list-date-bg.png);
				}

				[class^='date-']{
					display: block;
					width: 100%;
					text-align: center;
				}

				.date-day{
					margin-top:6px;
					@include font-size(5.4,5.4);
				}

				.date-month{
					@include font-size(1.5,1.5);
				}
		}
	}

The code gets compiled correctly but Autoprefixer breaks, however this does not happen when running Sass 3.3.5. I am currently using Codekit 2.0.4

Mixin Above:

	@mixin font-size($size:1.6, $line: $size * 1.5){
	    line-height: ($line * 10) + px;
	    font-size:   ($size * 10) + px;
	}

Can someone double check this.

**Comment by xzyfer** [comment] 2015-01-02 05:34
Specs added https://github.com/sass/sass-spec/pull/175

**Comment by wintercounter** [comment] 2015-01-02 11:28
SassMeister was using 3.1 beta for a little bit and tried it.

Test Code:
```scss
.outer {
  content: 'outer';
  
  @at-root {
    .inner {
      content: 'inner';
    }
  }
}
```

Wrong Output:
```css
.outer {
  content: 'outer';
  @at-root {
    .inner {
      content: 'inner'; } }
 }
```

Expected:
```css
.outer {
  content: 'outer';
}
.inner {
  content: 'inner';
}
```

**Comment by xzyfer** [comment] 2015-01-02 11:31
Yep. I've started work in this today. It'll be in 3.2.

**Comment by wintercounter** [comment] 2015-01-02 11:49
Awesome, keep up the good work! Libsass is a holy grail for me because it's performance. I still achieved 10 sec compilation time because of the huge codebase and many (not kidding, thousands) of map-get. (I know it has improvements in 3.1 but node-sass has still only 3.0). With the Ruby compiler this was around 40-50 sec, you can imagine how funny is that to work with :D

**Comment by HugoGiraudel** [comment] 2015-01-02 23:51
All tests for `@at-root` are now written, including nifty ones. If we need more, I'll add more. Some of them still needs to be merged though (https://github.com/sass/sass-spec/pull/217).

**Comment by xzyfer** [comment] 2015-01-07 02:49
This is implemented on master. It'll be in 3.2.

**Closed** 2015-01-07 02:49 UTC
Labels: bounty, feature, test written

**Comment by emagnier** [comment] 2015-01-07 02:53
:+1: Thanks a lot!

**Comment by dawidk92** [comment] 2015-01-21 12:37
+1

**Comment by sp90** [comment] 2015-02-12 12:03
So is this usable now?

**Comment by xzyfer** [comment] 2015-02-12 13:21
This will be in the next version on Libsass.

**Comment by ciampo** [comment] 2015-06-16 16:38
Any update on this?

**Comment by mzgol** [comment] 2015-06-16 16:55
@ciampo This works in latest libsass, do you experience any problems?

**Comment by ciampo** [comment] 2015-06-17 13:28
@mzgol Having some issues while compiling the sass through gulp-sass, but I guess the problem is the gulp-sass not using an updated version of node-sass

**Comment by mzgol** [comment] 2015-06-17 13:31
@ciampo From what I see `gulp-sass` 2.0.1 depends on `node-sass` 3.2.0 i.e. the latest. It should work unless you use an outdated `gulp-sass`.

**Comment by ciampo** [comment] 2015-06-17 13:35
@mzgol you're actually right, just realised we were using an outdated version of  `gulp-sass` - all fixed. Sorry and thanks!
