### ISSUE TITLE
Single quotes are removed in data uri during compilation

### ISSUE THREAD

**Issue by BboyKeen** [sass/libsass#1806] opened 2015-12-28 00:13 UTC
Hi,

I've just encontered a bug when using inlined SVG

```css
div {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' width='32' height='24' viewBox='0 0 32 24'><polygon points='0,0 32,0 16,24' style='fill: rgb%2851, 51, 51%29'></polygon></svg>");
}
```
produces 

```css
div {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns=http://www.w3.org/2000/svg version=1.1 width=32 height=24 viewBox=0 0 32 24><polygon points=0,0 32,0 16,24 style=fill: rgb%2851, 51, 51%29></polygon></svg>");
}
```

You'll notice that all single quotes are removed after compilation, which results in bad SVG.

When using base64 encoded resource, there is no problem.

I'm using 
```
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
```

**Comment by xzyfer** [comment] 2015-12-28 02:31
Thanks for the report @BboyKeen, however I am unable to reproduce this with the node-sass / LibSass versions specified.

You can see the results with this handy online node-sass compiler - http://www.sassmeister.com/gist/2c883b2327e12ea2e55d

**Comment by xzyfer** [comment] 2015-12-28 02:33
Maybe you've mistake the node-sass version being used, or there is another tool in your pipeline that is breaking the CSS after node-sass runs. 

I'm closing this issue because I cannot reproduce it. If new information comes up I can reopen it.

**Closed by xzyfer** 2015-12-28 02:33 UTC
Labels: Invalid - Not Reproducible

**Comment by BboyKeen** [comment] 2015-12-28 10:46
You're right. After deeper research, it appears that the faulty plugin in my pipeline is gulp-concat-css which rebases the svg url in the wrong way.

Sorry for the inconvenience.
