### ISSUE TITLE
Type discrepancy for quoted colors (strings)

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1281] opened 2015-06-17 14:30 UTC
**TEST:**
```scss
$string: "green"; // notice quotes

.test {
  type: type-of($string);
}
```

**EXPECTED:** (Ruby Sass)
```scss
.test {
  type: string;
}
```

**ACTUAL:** (LibSass 3.2.5)
```scss
.test {
  type: color;
}
```

On a similar note, `type-of(unquote("green"))` should also be a `string`.

**Comment by CHedgren** [comment] 2015-06-17 21:02
But '#fff'  would not have color type.

**Comment by mgreter** [comment] 2015-06-18 00:20
This is actually easy to fix. We actually have a specific code part for exactly that falty behavior?

in functions.cpp `type-of($value)`
```C
- if (ctx.names_to_colors.count(str)) {
-   return new (ctx.mem) String_Constant(pstate, "color");
- }
```

**Comment by mgreter** [comment] 2015-06-23 18:11
Duplicate of #1280

**Comment by xzyfer** [comment] 2015-06-29 05:10
Specs added https://github.com/sass/sass-spec/pull/412

**Closed** 2015-07-08 06:10 UTC
Labels: Bug - Confirmed, Dev - PR Ready, test written
