### ISSUE TITLE
variable compilation bug in "margin" shorthand property

### ISSUE THREAD

**Issue by callmecavs** [sass/libsass#893] opened 2015-02-20 16:40 UTC
This Sass:
```css
$gutter: 20px;

.row {
  margin: 0 -$gutter;
}
```
Compiles to this CSS with **libsass**:
```
.row {
  margin: -20px;
}
```
But with **ruby sass** compiles to this CSS:
```
.row {
  margin: 0 -20px;
}
```
This compiles as expected:
```css
$gutter: 20px;

.row {
  margin: 0 (-$gutter);
}
```

**Comment by akhleung** [comment] 2015-02-20 18:00
Hmm, looks like the parser is interpreting the expression as a subtraction instead of a list of two elements.

**Comment by xzyfer** [comment] 2015-02-21 01:34
Thanks for the report @callmecavs . I can confirm this is still present on master.

Could you please open sass-spec PR? Here's a good example to get you started sass/sass-spec#260

**Comment by callmecavs** [comment] 2015-02-23 23:23
@xzyfer will get it done this week

**Comment by callmecavs** [comment] 2015-02-24 00:10
here's the pr: https://github.com/sass/sass-spec/pull/268

**Comment by mgreter** [comment] 2015-03-09 04:30
Actually ruby sass seems to compile to the same output:

```
$gutter: 20px;

.row {
  margin: 0 -$gutter;
}
```

Also verified on http://sassmeister.com/. It also seems to be true for ruby sass down to version 3.2.19 (oldest available on sassmeister). Closing this as `not reproducible`.

**Closed by mgreter** 2015-03-09 04:30 UTC
Labels: bug, needs test
