### ISSUE TITLE
font property with normal line-height and face variable does not parse

### ISSUE THREAD

**Issue by dpatti** [sass/libsass#2180] opened 2016-09-19 18:05 UTC
input
```scss
$face: sans-serif;

a {
  font: 12px/normal $face;
}
```

[libsass 3.5.5] [1]
```
Error: 12px/normal isn't a valid CSS value.
        on line 4 of stdin
>>   font: 12px/normal $face;
   --------^ 
```

ruby sass 3.4.21
```css
a {
  font: 12px/normal sans-serif;
}
```

version info:
```cmd
$ node-sass --version
node-sass       3.10.0  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```

Note that changing the line height to an integer (such as `12px/3 $face`) or inlining the variable (such as `12px/normal sans-serif`) both work.

[1]: http://libsass.ocbnet.ch/srcmap/#JGZhY2U6IHNhbnMtc2VyaWY7CgphIHsKICBmb250OiAxMnB4L25vcm1hbCAkZmFjZTsKfQ==

**Comment by nschonni** [comment] 2016-09-19 18:36
This appears to be a duplicate of #2149

**Comment by dpatti** [comment] 2016-09-19 19:20
You think so, even though [this](http://libsass.ocbnet.ch/srcmap/#YSB7CiAgZm9udDogMTJweC9ub3JtYWwgc2Fucy1zZXJpZjsKfQ==) compiles fine?

**Comment by xzyfer** [comment] 2016-09-20 00:08
They cause is the same, the result is different. We treating `\` as a division operation when it should a CSS separator.

**Closed** 2016-09-20 00:08 UTC
