### ISSUE TITLE
libsass 3.4: file context fails on missing input path, event though it is provided in constructor

### ISSUE THREAD

**Issue by gauteh** [sass/libsass#2257] opened 2016-12-20 06:48 UTC
### Using file context with libsass based on example fails on libsass 3.4

Hi,

I am using libsass based on the example provided for the file context [here](https://github.com/sass/libsass/blob/master/docs/api-doc.md#compiling-your-code). However, I've had multiple reports of breakage (https://github.com/astroidmail/astroid/issues/248, https://github.com/astroidmail/astroid/issues/244) with libsass 3.4.0 (default on Debian and Arch Linux), getting the error:

```
Internal Error: File context has no input path
```

I am loading sass in this way (https://github.com/astroidmail/astroid/blob/master/src/modes/thread_view/theme.cc#L96):
```
    const char * scsspath = "path/to/file.scss";

    struct Sass_File_Context* file_ctx = sass_make_file_context(scsspath);
    struct Sass_Options* options = sass_file_context_get_options(file_ctx);
    struct Sass_Context* context = sass_file_context_get_context(file_ctx);
    sass_option_set_precision(options, 1);
    sass_option_set_source_comments(options, true);

    sass_file_context_set_options(file_ctx, options);

    int status = sass_compile_file_context (file_ctx);

    if (status != 0) {
      const char * err = sass_context_get_error_message (context);
      ustring erru (err);
      LOG (error) << "theme: error processing: " << erru;

      throw runtime_error (
          ustring::compose ("theme: could not process scss: %1", erru).c_str ());
    }

    const char * output = sass_context_get_output_string(context);
    ustring output_str(output);
    sass_delete_file_context (file_ctx);

    return output_str;
```

version info:
```
libsass         3.4.0   (Sass Compiler) [C/C++]
```

**Comment by gauteh** [comment] 2016-12-20 08:43
From looking at git blame the culprit might be 6a5444b2, if I remove the call to `sass_file_context_set_options` the error is lost. I cannot inspect the structs more in depth using gdb at this point since I do not have access to the complete type in gdb.

**Comment by mgreter** [comment] 2016-12-20 09:04
@gauteh the commit you mention (https://github.com/sass/libsass/commit/6a5444b2e7420b79fb53da4afec05db524c1b3ef) is not part of libsass 3.4.0? So I'm confused if your report is against master or libsass 3.4.0 (as you stated in your first post)? Also does your example above exhibit the problem or is that just for illustration? Thanks!

**Comment by gauteh** [comment] 2016-12-20 09:08
@mgreter Ah - sorry, I did not notice that. The problem is still with libsass 3.4.0. The example exhibits the problem, If I change it to (https://github.com/astroidmail/astroid/pull/249/commits/b44b9fcd50f5ba9bfe728d426ddb23001eda5199):

```
    struct Sass_File_Context* file_ctx = sass_make_file_context(scsspath);
    struct Sass_Context* context = sass_file_context_get_context(file_ctx);
    sass_option_set_precision((Sass_Options*) file_ctx, 1);
    sass_option_set_source_comments((Sass_Options*) file_ctx, true);

    int status = sass_compile_file_context (file_ctx);

    if (status != 0) {
      const char * err = sass_context_get_error_message (context);
      ustring erru (err);
      LOG (error) << "theme: error processing: " << erru;

      throw runtime_error (
          ustring::compose ("theme: could not process scss: %1", erru).c_str ());
    }

    const char * output = sass_context_get_output_string(context);
    ustring output_str(output);
    sass_delete_file_context (file_ctx);

    return output_str;
  }
``` 

it works.

**Comment by mgreter** [comment] 2016-12-20 10:06
OK, I was able to verify the issue on linux. Could not reproduce on windows with mingw64 and msys2.

**Comment by mgreter** [comment] 2016-12-20 10:20
Can you try out the fix in https://github.com/sass/libsass/pull/2259 ?

**Comment by gauteh** [comment] 2016-12-20 12:09
Hi @mgreter, thanks - your proposed fix works fine (and should be portable if you decide to change the class structure later on). I do not have libsass set up in a development environment at the moment, so I won't have the time to test #2259 now unfortunately. It does look like it would fix the issue though.

**Comment by mgreter** [comment] 2016-12-21 00:10
Closing as resolved

**Closed by mgreter** 2016-12-21 00:10 UTC
Labels: Bug - Confirmed, C API

**Comment by gauteh** [comment] 2016-12-21 16:16
Thanks 😊


ons. 21. des. 2016 kl. 01.10 skrev Marcel Greter <notifications@github.com>:
