### ISSUE TITLE
Lines ending in '\' ignore last character and carriage return

### ISSUE THREAD

**Issue by blabute** [sass/libsass#1791] opened 2015-12-16 21:00 UTC
It seems when a line in the .scss file ends with a backslash, the backlash and the carriage return are ignored.

.scss 
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```
Resulting .css
```
/--------------------------------------------- TEST
*---------------------------------------------*/
```

Adding another character to the end will give the expected result as seen below.
.scss 
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```
Resulting .css
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```

**Comment by xzyfer** [comment] 2015-12-27 07:10
@blabute I'm confused. The supplied code does not compile with Sass.

**Comment by blabute** [comment] 2015-12-29 13:14
My apologies. Below is a code that will compile.

/*---------------------------------------------------------------------------*\
    TEST
\*---------------------------------------------------------------------------*/
    header {
        
        background-color: blue;
        
    } // header

**Comment by xzyfer** [comment] 2015-12-30 02:22
Thanks for the update. This is a duplicate of https://github.com/sass/libsass/issues/1294. Subscribe to that issue for future updates.

**Closed by xzyfer** 2015-12-30 02:22 UTC
Labels: Bug - Maybe, Bug - Wording
