### ISSUE TITLE
Carriage return left in CSS when compiling multiline rules on windows

### ISSUE THREAD

**Issue by c99pjn** [sass/libsass#2693] opened 2018-07-10 11:26 UTC
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
item {
  padding-left: calc(
    24px
  )
}
```

With control characters

```scss
item {<CR><LF>
  padding-left: calc(<CR><LF>
    24px<CR><LF>
  )<CR><LF>
}
```

## Actual results (as printed in cmd)

[todo]: # (update version info!)

[libsass 3.5.2-72-g38f4-dirty][1]
sassc 3.4.8-5-g6a64-dirty

```css
item {
 24px); }-left: calc(
```

Written to file with control characters

```css
item{padding-left:calc(<CR>
 24px)}<LF>
```

## Expected result

[todo]: # (update version info!)

```css
item{padding-left:calc(24px)} <LF>
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by mgreter** [comment] 2018-12-14 01:09
Probably duplicate of https://github.com/sass/libsass/issues/2743

**Comment by bholloway** [comment] 2019-04-03 10:54
Our results show this to be independent of `linefeed` option, implying **not** a duplicate of #2743.

Refer to [this comment](https://github.com/bholloway/resolve-url-loader/issues/107#issuecomment-479433221) for breaking repo and analysis.

**some context**

The webpack `resolve-url-loader` is downstream from libsass. It performs `url()` rewriting.

For Windows users with multiline declarations this bug will fail their build. bholloway/resolve-url-loader#107.

In libsass the orphan `CR` in the output doesn't imply a newline. However `postcss` parser will consider this as a newline. This mismatch manifests as a line-number error in the source-map.

Would be really good to get this bug fixed. 🙏 

In the interim we will strip orphan `CR` from the incoming `css`.

**Comment by glebm** [comment] 2019-04-03 15:43
This is already fixed on master (https://github.com/sass/libsass/pull/2849)

**Closed** 2019-04-15 05:57 UTC
Labels: Bug - Whitespace
