### ISSUE TITLE
Can't compile node-sass on FreeBSD 11.1

### ISSUE THREAD

**Issue by duncan-bayne** [sass/libsass#2453] opened 2017-07-31 00:14 UTC
I am having difficulty installing node-sass on FreeBSD 11.1, and I believe it's because libsass isn't compiling.

When I run `npm rebuild node-sass`:

```
In file included from /usr/include/c++/v1/stddef.h:40:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
gmake: *** [src/libsass.target.mk:141: Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gmake: Leaving directory '/usr/home/duncan/project/frontend/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/home/duncan/project/frontend/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System FreeBSD 11.1-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/home/duncan/project/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/home/duncan/project/frontend/node_modules/node-sass
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

I'm on Node 8.1.4 and NPM 5.0.4.

**Comment by nschonni** [comment] 2017-07-31 04:50
Duplicate of https://github.com/sass/node-sass/issues/1911

**Comment by duncan-bayne** [comment] 2017-08-03 06:23
@saper :wave: ... let me know if I can help in any way.  I'm a bit of a FreeBSD n00b though.

**Comment by saper** [comment] 2017-08-03 06:39
No worries, this is solved already, I need to check where I saw the fix.

**Comment by saper** [comment] 2017-08-06 20:31
This is https://github.com/nodejs/node/issues/14076 and it is already fixed in node and is already in the Release Candidate https://github.com/nodejs/node/issues/14076#issuecomment-320024766 - so either downgrade to node 6 or wait a bit.

**Closed by saper** 2017-08-06 20:31 UTC
Labels: Build

**Comment by saper** [comment] 2017-08-10 20:35
Node 8.3.0 has just made it to the [FreeBSD ports](https://svnweb.freebsd.org/ports?view=revision&revision=447673).

**Comment by saper** [comment] 2017-09-10 11:13
FYI: I have uploaded FreeBSD bindings for node 4,6 and 8 for i386 and amd64 architectures.
